#ifndef _ENUMS_H
#define _ENUMS_H

#ifndef SCILEXER_H
#include "SciLexer.h"
#endif

#ifndef _SCINTILLANOTIFICATIONS_H
#include "ScintillaNotifications.h"
#endif

void export_enums();

//lint -e849 Symbol 'VkKeys::PYSCR_VK_HANGUL' has same enumerator value '21' as enumerator 'PYSCR_VK_KANA'
// This is expected. There are several keys with duplicate identifiers.

enum VkKeys
{
	PYSCR_VK_BACK = 0x08,
	PYSCR_VK_TAB = 0x09,
	PYSCR_VK_CLEAR = 0x0C,
	PYSCR_VK_RETURN = 0x0D,
	PYSCR_VK_SHIFT = 0x10,
	PYSCR_VK_CONTROL = 0x11,
	PYSCR_VK_MENU = 0x12,
	PYSCR_VK_PAUSE = 0x13,
	PYSCR_VK_CAPITAL = 0x14,
	PYSCR_VK_KANA = 0x15,
	PYSCR_VK_HANGUL = 0x15,
	PYSCR_VK_JUNJA = 0x17,
	PYSCR_VK_FINAL = 0x18,
	PYSCR_VK_HANJA = 0x19,
	PYSCR_VK_KANJI = 0x19,
	PYSCR_VK_ESCAPE = 0x1B,
	PYSCR_VK_CONVERT = 0x1C,
	PYSCR_VK_NONCONVERT = 0x1D,
	PYSCR_VK_ACCEPT = 0x1E,
	PYSCR_VK_MODECHANGE = 0x1F,
	PYSCR_VK_SPACE = 0x20,
	PYSCR_VK_PRIOR = 0x21,
	PYSCR_VK_NEXT = 0x22,
	PYSCR_VK_END = 0x23,
	PYSCR_VK_HOME = 0x24,
	PYSCR_VK_LEFT = 0x25,
	PYSCR_VK_UP = 0x26,
	PYSCR_VK_RIGHT = 0x27,
	PYSCR_VK_DOWN = 0x28,
	PYSCR_VK_SELECT = 0x29,
	PYSCR_VK_PRINT = 0x2A,
	PYSCR_VK_EXECUTE = 0x2B,
	PYSCR_VK_SNAPSHOT = 0x2C,
	PYSCR_VK_INSERT = 0x2D,
	PYSCR_VK_DELETE = 0x2E,
	PYSCR_VK_HELP = 0x2F,
	PYSCR_VK_0 = 0x30,
	PYSCR_VK_1 = 0x31,
	PYSCR_VK_2 = 0x32,
	PYSCR_VK_3 = 0x33,
	PYSCR_VK_4 = 0x34,
	PYSCR_VK_5 = 0x35,
	PYSCR_VK_6 = 0x36,
	PYSCR_VK_7 = 0x37,
	PYSCR_VK_8 = 0x38,
	PYSCR_VK_9 = 0x39,
	PYSCR_VK_A = 0x41,
	PYSCR_VK_B = 0x42,
	PYSCR_VK_C = 0x43,
	PYSCR_VK_D = 0x44,
	PYSCR_VK_E = 0x45,
	PYSCR_VK_F = 0x46,
	PYSCR_VK_G = 0x47,
	PYSCR_VK_H = 0x48,
	PYSCR_VK_I = 0x49,
	PYSCR_VK_J = 0x4A,
	PYSCR_VK_K = 0x4B,
	PYSCR_VK_L = 0x4C,
	PYSCR_VK_M = 0x4D,
	PYSCR_VK_N = 0x4E,
	PYSCR_VK_O = 0x4F,
	PYSCR_VK_P = 0x50,
	PYSCR_VK_Q = 0x51,
	PYSCR_VK_R = 0x52,
	PYSCR_VK_S = 0x53,
	PYSCR_VK_T = 0x54,
	PYSCR_VK_U = 0x55,
	PYSCR_VK_V = 0x56,
	PYSCR_VK_W = 0x57,
	PYSCR_VK_X = 0x58,
	PYSCR_VK_Y = 0x59,
	PYSCR_VK_Z = 0x5A,
	PYSCR_VK_LWIN = 0x5B,
	PYSCR_VK_RWIN = 0x5C,
	PYSCR_VK_APPS = 0x5D,
	PYSCR_VK_SLEEP = 0x5F,
	PYSCR_VK_NUMPAD0 = 0x60,
	PYSCR_VK_NUMPAD1 = 0x61,
	PYSCR_VK_NUMPAD2 = 0x62,
	PYSCR_VK_NUMPAD3 = 0x63,
	PYSCR_VK_NUMPAD4 = 0x64,
	PYSCR_VK_NUMPAD5 = 0x65,
	PYSCR_VK_NUMPAD6 = 0x66,
	PYSCR_VK_NUMPAD7 = 0x67,
	PYSCR_VK_NUMPAD8 = 0x68,
	PYSCR_VK_NUMPAD9 = 0x69,
	PYSCR_VK_MULTIPLY = 0x6A,
	PYSCR_VK_ADD = 0x6B,
	PYSCR_VK_SEPARATOR = 0x6C,
	PYSCR_VK_SUBTRACT = 0x6D,
	PYSCR_VK_DECIMAL = 0x6E,
	PYSCR_VK_DIVIDE = 0x6F,
	PYSCR_VK_F1 = 0x70,
	PYSCR_VK_F2 = 0x71,
	PYSCR_VK_F3 = 0x72,
	PYSCR_VK_F4 = 0x73,
	PYSCR_VK_F5 = 0x74,
	PYSCR_VK_F6 = 0x75,
	PYSCR_VK_F7 = 0x76,
	PYSCR_VK_F8 = 0x77,
	PYSCR_VK_F9 = 0x78,
	PYSCR_VK_F10 = 0x79,
	PYSCR_VK_F11 = 0x7A,
	PYSCR_VK_F12 = 0x7B,
	PYSCR_VK_F13 = 0x7C,
	PYSCR_VK_F14 = 0x7D,
	PYSCR_VK_F15 = 0x7E,
	PYSCR_VK_F16 = 0x7F,
	PYSCR_VK_F17 = 0x80,
	PYSCR_VK_F18 = 0x81,
	PYSCR_VK_F19 = 0x82,
	PYSCR_VK_F20 = 0x83,
	PYSCR_VK_F21 = 0x84,
	PYSCR_VK_F22 = 0x85,
	PYSCR_VK_F23 = 0x86,
	PYSCR_VK_F24 = 0x87,
	PYSCR_VK_NUMLOCK = 0x90,
	PYSCR_VK_SCROLL = 0x91,
	PYSCR_VK_OEM_NEC_EQUAL = 0x92,
	PYSCR_VK_OEM_FJ_JISHO = 0x92,
	PYSCR_VK_OEM_FJ_MASSHOU = 0x93,
	PYSCR_VK_OEM_FJ_TOUROKU = 0x94,
	PYSCR_VK_OEM_FJ_LOYA = 0x95,
	PYSCR_VK_OEM_FJ_ROYA = 0x96,
	PYSCR_VK_LSHIFT = 0xA0,
	PYSCR_VK_RSHIFT = 0xA1,
	PYSCR_VK_LCONTROL = 0xA2,
	PYSCR_VK_RCONTROL = 0xA3,
	PYSCR_VK_LMENU = 0xA4,
	PYSCR_VK_RMENU = 0xA5,
	PYSCR_VK_BROWSER_BACK = 0xA6,
	PYSCR_VK_BROWSER_FORWARD = 0xA7,
	PYSCR_VK_BROWSER_REFRESH = 0xA8,
	PYSCR_VK_BROWSER_STOP = 0xA9,
	PYSCR_VK_BROWSER_SEARCH = 0xAA,
	PYSCR_VK_BROWSER_FAVORITES = 0xAB,
	PYSCR_VK_BROWSER_HOME = 0xAC,
	PYSCR_VK_VOLUME_MUTE = 0xAD,
	PYSCR_VK_VOLUME_DOWN = 0xAE,
	PYSCR_VK_VOLUME_UP = 0xAF,
	PYSCR_VK_MEDIA_NEXT_TRACK = 0xB0,
	PYSCR_VK_MEDIA_PREV_TRACK = 0xB1,
	PYSCR_VK_MEDIA_STOP = 0xB2,
	PYSCR_VK_MEDIA_PLAY_PAUSE = 0xB3,
	PYSCR_VK_LAUNCH_MAIL = 0xB4,
	PYSCR_VK_LAUNCH_MEDIA_SELECT = 0xB5,
	PYSCR_VK_LAUNCH_APP1 = 0xB6,
	PYSCR_VK_LAUNCH_APP2 = 0xB7,
	PYSCR_VK_OEM_1 = 0xBA,
	PYSCR_VK_OEM_PLUS = 0xBB,
	PYSCR_VK_OEM_COMMA = 0xBC,
	PYSCR_VK_OEM_MINUS = 0xBD,
	PYSCR_VK_OEM_PERIOD = 0xBE,
	PYSCR_VK_OEM_2 = 0xBF,
	PYSCR_VK_OEM_3 = 0xC0,
	PYSCR_VK_OEM_4 = 0xDB,
	PYSCR_VK_OEM_5 = 0xDC,
	PYSCR_VK_OEM_6 = 0xDD,
	PYSCR_VK_OEM_7 = 0xDE,
	PYSCR_VK_OEM_8 = 0xDF,
	PYSCR_VK_OEM_AX = 0xE1,
	PYSCR_VK_OEM_102 = 0xE2,
	PYSCR_VK_ICO_HELP = 0xE3,
	PYSCR_VK_ICO_00 = 0xE4,
	PYSCR_VK_PROCESSKEY = 0xE5,
	PYSCR_VK_ICO_CLEAR = 0xE6,
	PYSCR_VK_PACKET = 0xE7,
	PYSCR_VK_OEM_RESET = 0xE9,
	PYSCR_VK_OEM_JUMP = 0xEA,
	PYSCR_VK_OEM_PA1 = 0xEB,
	PYSCR_VK_OEM_PA2 = 0xEC,
	PYSCR_VK_OEM_PA3 = 0xED,
	PYSCR_VK_OEM_WSCTRL = 0xEE,
	PYSCR_VK_OEM_CUSEL = 0xEF,
	PYSCR_VK_OEM_ATTN = 0xF0,
	PYSCR_VK_OEM_FINISH = 0xF1,
	PYSCR_VK_OEM_COPY = 0xF2,
	PYSCR_VK_OEM_AUTO = 0xF3,
	PYSCR_VK_OEM_ENLW = 0xF4,
	PYSCR_VK_OEM_BACKTAB = 0xF5,
	PYSCR_VK_ATTN = 0xF6,
	PYSCR_VK_CRSEL = 0xF7,
	PYSCR_VK_EXSEL = 0xF8,
	PYSCR_VK_EREOF = 0xF9,
	PYSCR_VK_PLAY = 0xFA,
	PYSCR_VK_ZOOM = 0xFB,
	PYSCR_VK_NONAME = 0xFC,
	PYSCR_VK_PA1 = 0xFD,
	PYSCR_VK_OEM_CLEAR = 0xFE
};
//lint +e849

/* ++Autogenerated ---------------------------------------------- */
enum WhiteSpace
{
	PYSCR_SCWS_INVISIBLE = SCWS_INVISIBLE,
	PYSCR_SCWS_VISIBLEALWAYS = SCWS_VISIBLEALWAYS,
	PYSCR_SCWS_VISIBLEAFTERINDENT = SCWS_VISIBLEAFTERINDENT,
	PYSCR_SCWS_VISIBLEONLYININDENT = SCWS_VISIBLEONLYININDENT
};

enum TabDrawMode
{
	PYSCR_SCTD_LONGARROW = SCTD_LONGARROW,
	PYSCR_SCTD_STRIKEOUT = SCTD_STRIKEOUT
};

enum EndOfLine
{
	PYSCR_SC_EOL_CRLF = SC_EOL_CRLF,
	PYSCR_SC_EOL_CR = SC_EOL_CR,
	PYSCR_SC_EOL_LF = SC_EOL_LF
};

enum IMEInteraction
{
	PYSCR_SC_IME_WINDOWED = SC_IME_WINDOWED,
	PYSCR_SC_IME_INLINE = SC_IME_INLINE
};

enum Alpha
{
	PYSCR_SC_ALPHA_TRANSPARENT = SC_ALPHA_TRANSPARENT,
	PYSCR_SC_ALPHA_OPAQUE = SC_ALPHA_OPAQUE,
	PYSCR_SC_ALPHA_NOALPHA = SC_ALPHA_NOALPHA
};

enum CursorShape
{
	PYSCR_SC_CURSORNORMAL = SC_CURSORNORMAL,
	PYSCR_SC_CURSORARROW = SC_CURSORARROW,
	PYSCR_SC_CURSORWAIT = SC_CURSORWAIT,
	PYSCR_SC_CURSORREVERSEARROW = SC_CURSORREVERSEARROW
};

enum MarkerSymbol
{
	PYSCR_SC_MARK_CIRCLE = SC_MARK_CIRCLE,
	PYSCR_SC_MARK_ROUNDRECT = SC_MARK_ROUNDRECT,
	PYSCR_SC_MARK_ARROW = SC_MARK_ARROW,
	PYSCR_SC_MARK_SMALLRECT = SC_MARK_SMALLRECT,
	PYSCR_SC_MARK_SHORTARROW = SC_MARK_SHORTARROW,
	PYSCR_SC_MARK_EMPTY = SC_MARK_EMPTY,
	PYSCR_SC_MARK_ARROWDOWN = SC_MARK_ARROWDOWN,
	PYSCR_SC_MARK_MINUS = SC_MARK_MINUS,
	PYSCR_SC_MARK_PLUS = SC_MARK_PLUS,
	PYSCR_SC_MARK_VLINE = SC_MARK_VLINE,
	PYSCR_SC_MARK_LCORNER = SC_MARK_LCORNER,
	PYSCR_SC_MARK_TCORNER = SC_MARK_TCORNER,
	PYSCR_SC_MARK_BOXPLUS = SC_MARK_BOXPLUS,
	PYSCR_SC_MARK_BOXPLUSCONNECTED = SC_MARK_BOXPLUSCONNECTED,
	PYSCR_SC_MARK_BOXMINUS = SC_MARK_BOXMINUS,
	PYSCR_SC_MARK_BOXMINUSCONNECTED = SC_MARK_BOXMINUSCONNECTED,
	PYSCR_SC_MARK_LCORNERCURVE = SC_MARK_LCORNERCURVE,
	PYSCR_SC_MARK_TCORNERCURVE = SC_MARK_TCORNERCURVE,
	PYSCR_SC_MARK_CIRCLEPLUS = SC_MARK_CIRCLEPLUS,
	PYSCR_SC_MARK_CIRCLEPLUSCONNECTED = SC_MARK_CIRCLEPLUSCONNECTED,
	PYSCR_SC_MARK_CIRCLEMINUS = SC_MARK_CIRCLEMINUS,
	PYSCR_SC_MARK_CIRCLEMINUSCONNECTED = SC_MARK_CIRCLEMINUSCONNECTED,
	PYSCR_SC_MARK_BACKGROUND = SC_MARK_BACKGROUND,
	PYSCR_SC_MARK_DOTDOTDOT = SC_MARK_DOTDOTDOT,
	PYSCR_SC_MARK_ARROWS = SC_MARK_ARROWS,
	PYSCR_SC_MARK_PIXMAP = SC_MARK_PIXMAP,
	PYSCR_SC_MARK_FULLRECT = SC_MARK_FULLRECT,
	PYSCR_SC_MARK_LEFTRECT = SC_MARK_LEFTRECT,
	PYSCR_SC_MARK_AVAILABLE = SC_MARK_AVAILABLE,
	PYSCR_SC_MARK_UNDERLINE = SC_MARK_UNDERLINE,
	PYSCR_SC_MARK_RGBAIMAGE = SC_MARK_RGBAIMAGE,
	PYSCR_SC_MARK_BOOKMARK = SC_MARK_BOOKMARK,
	PYSCR_SC_MARK_VERTICALBOOKMARK = SC_MARK_VERTICALBOOKMARK,
	PYSCR_SC_MARK_CHARACTER = SC_MARK_CHARACTER
};

enum MarkerOutline
{
	PYSCR_SC_MARKNUM_FOLDEREND = SC_MARKNUM_FOLDEREND,
	PYSCR_SC_MARKNUM_FOLDEROPENMID = SC_MARKNUM_FOLDEROPENMID,
	PYSCR_SC_MARKNUM_FOLDERMIDTAIL = SC_MARKNUM_FOLDERMIDTAIL,
	PYSCR_SC_MARKNUM_FOLDERTAIL = SC_MARKNUM_FOLDERTAIL,
	PYSCR_SC_MARKNUM_FOLDERSUB = SC_MARKNUM_FOLDERSUB,
	PYSCR_SC_MARKNUM_FOLDER = SC_MARKNUM_FOLDER,
	PYSCR_SC_MARKNUM_FOLDEROPEN = SC_MARKNUM_FOLDEROPEN
};

enum MarginType
{
	PYSCR_SC_MARGIN_SYMBOL = SC_MARGIN_SYMBOL,
	PYSCR_SC_MARGIN_NUMBER = SC_MARGIN_NUMBER,
	PYSCR_SC_MARGIN_BACK = SC_MARGIN_BACK,
	PYSCR_SC_MARGIN_FORE = SC_MARGIN_FORE,
	PYSCR_SC_MARGIN_TEXT = SC_MARGIN_TEXT,
	PYSCR_SC_MARGIN_RTEXT = SC_MARGIN_RTEXT,
	PYSCR_SC_MARGIN_COLOUR = SC_MARGIN_COLOUR
};

enum StylesCommon
{
	PYSCR_STYLE_DEFAULT = STYLE_DEFAULT,
	PYSCR_STYLE_LINENUMBER = STYLE_LINENUMBER,
	PYSCR_STYLE_BRACELIGHT = STYLE_BRACELIGHT,
	PYSCR_STYLE_BRACEBAD = STYLE_BRACEBAD,
	PYSCR_STYLE_CONTROLCHAR = STYLE_CONTROLCHAR,
	PYSCR_STYLE_INDENTGUIDE = STYLE_INDENTGUIDE,
	PYSCR_STYLE_CALLTIP = STYLE_CALLTIP,
	PYSCR_STYLE_FOLDDISPLAYTEXT = STYLE_FOLDDISPLAYTEXT,
	PYSCR_STYLE_LASTPREDEFINED = STYLE_LASTPREDEFINED,
	PYSCR_STYLE_MAX = STYLE_MAX
};

enum CharacterSet
{
	PYSCR_SC_CHARSET_ANSI = SC_CHARSET_ANSI,
	PYSCR_SC_CHARSET_DEFAULT = SC_CHARSET_DEFAULT,
	PYSCR_SC_CHARSET_BALTIC = SC_CHARSET_BALTIC,
	PYSCR_SC_CHARSET_CHINESEBIG5 = SC_CHARSET_CHINESEBIG5,
	PYSCR_SC_CHARSET_EASTEUROPE = SC_CHARSET_EASTEUROPE,
	PYSCR_SC_CHARSET_GB2312 = SC_CHARSET_GB2312,
	PYSCR_SC_CHARSET_GREEK = SC_CHARSET_GREEK,
	PYSCR_SC_CHARSET_HANGUL = SC_CHARSET_HANGUL,
	PYSCR_SC_CHARSET_MAC = SC_CHARSET_MAC,
	PYSCR_SC_CHARSET_OEM = SC_CHARSET_OEM,
	PYSCR_SC_CHARSET_RUSSIAN = SC_CHARSET_RUSSIAN,
	PYSCR_SC_CHARSET_OEM866 = SC_CHARSET_OEM866,
	PYSCR_SC_CHARSET_CYRILLIC = SC_CHARSET_CYRILLIC,
	PYSCR_SC_CHARSET_SHIFTJIS = SC_CHARSET_SHIFTJIS,
	PYSCR_SC_CHARSET_SYMBOL = SC_CHARSET_SYMBOL,
	PYSCR_SC_CHARSET_TURKISH = SC_CHARSET_TURKISH,
	PYSCR_SC_CHARSET_JOHAB = SC_CHARSET_JOHAB,
	PYSCR_SC_CHARSET_HEBREW = SC_CHARSET_HEBREW,
	PYSCR_SC_CHARSET_ARABIC = SC_CHARSET_ARABIC,
	PYSCR_SC_CHARSET_VIETNAMESE = SC_CHARSET_VIETNAMESE,
	PYSCR_SC_CHARSET_THAI = SC_CHARSET_THAI,
	PYSCR_SC_CHARSET_8859_15 = SC_CHARSET_8859_15
};

enum CaseVisible
{
	PYSCR_SC_CASE_MIXED = SC_CASE_MIXED,
	PYSCR_SC_CASE_UPPER = SC_CASE_UPPER,
	PYSCR_SC_CASE_LOWER = SC_CASE_LOWER,
	PYSCR_SC_CASE_CAMEL = SC_CASE_CAMEL
};

enum FontWeight
{
	PYSCR_SC_WEIGHT_NORMAL = SC_WEIGHT_NORMAL,
	PYSCR_SC_WEIGHT_SEMIBOLD = SC_WEIGHT_SEMIBOLD,
	PYSCR_SC_WEIGHT_BOLD = SC_WEIGHT_BOLD
};

enum Element
{
	PYSCR_SC_ELEMENT_LIST = SC_ELEMENT_LIST,
	PYSCR_SC_ELEMENT_LIST_BACK = SC_ELEMENT_LIST_BACK,
	PYSCR_SC_ELEMENT_LIST_SELECTED = SC_ELEMENT_LIST_SELECTED,
	PYSCR_SC_ELEMENT_LIST_SELECTED_BACK = SC_ELEMENT_LIST_SELECTED_BACK,
	PYSCR_SC_ELEMENT_SELECTION_TEXT = SC_ELEMENT_SELECTION_TEXT,
	PYSCR_SC_ELEMENT_SELECTION_BACK = SC_ELEMENT_SELECTION_BACK,
	PYSCR_SC_ELEMENT_SELECTION_ADDITIONAL_TEXT = SC_ELEMENT_SELECTION_ADDITIONAL_TEXT,
	PYSCR_SC_ELEMENT_SELECTION_ADDITIONAL_BACK = SC_ELEMENT_SELECTION_ADDITIONAL_BACK,
	PYSCR_SC_ELEMENT_SELECTION_SECONDARY_TEXT = SC_ELEMENT_SELECTION_SECONDARY_TEXT,
	PYSCR_SC_ELEMENT_SELECTION_SECONDARY_BACK = SC_ELEMENT_SELECTION_SECONDARY_BACK,
	PYSCR_SC_ELEMENT_SELECTION_INACTIVE_TEXT = SC_ELEMENT_SELECTION_INACTIVE_TEXT,
	PYSCR_SC_ELEMENT_SELECTION_INACTIVE_BACK = SC_ELEMENT_SELECTION_INACTIVE_BACK,
	PYSCR_SC_ELEMENT_CARET = SC_ELEMENT_CARET,
	PYSCR_SC_ELEMENT_CARET_ADDITIONAL = SC_ELEMENT_CARET_ADDITIONAL,
	PYSCR_SC_ELEMENT_CARET_LINE_BACK = SC_ELEMENT_CARET_LINE_BACK,
	PYSCR_SC_ELEMENT_WHITE_SPACE = SC_ELEMENT_WHITE_SPACE,
	PYSCR_SC_ELEMENT_WHITE_SPACE_BACK = SC_ELEMENT_WHITE_SPACE_BACK,
	PYSCR_SC_ELEMENT_HOT_SPOT_ACTIVE = SC_ELEMENT_HOT_SPOT_ACTIVE,
	PYSCR_SC_ELEMENT_HOT_SPOT_ACTIVE_BACK = SC_ELEMENT_HOT_SPOT_ACTIVE_BACK,
	PYSCR_SC_ELEMENT_FOLD_LINE = SC_ELEMENT_FOLD_LINE,
	PYSCR_SC_ELEMENT_HIDDEN_LINE = SC_ELEMENT_HIDDEN_LINE
};

enum Layer
{
	PYSCR_SC_LAYER_BASE = SC_LAYER_BASE,
	PYSCR_SC_LAYER_UNDER_TEXT = SC_LAYER_UNDER_TEXT,
	PYSCR_SC_LAYER_OVER_TEXT = SC_LAYER_OVER_TEXT
};

enum IndicatorStyle
{
	PYSCR_INDIC_PLAIN = INDIC_PLAIN,
	PYSCR_INDIC_SQUIGGLE = INDIC_SQUIGGLE,
	PYSCR_INDIC_TT = INDIC_TT,
	PYSCR_INDIC_DIAGONAL = INDIC_DIAGONAL,
	PYSCR_INDIC_STRIKE = INDIC_STRIKE,
	PYSCR_INDIC_HIDDEN = INDIC_HIDDEN,
	PYSCR_INDIC_BOX = INDIC_BOX,
	PYSCR_INDIC_ROUNDBOX = INDIC_ROUNDBOX,
	PYSCR_INDIC_STRAIGHTBOX = INDIC_STRAIGHTBOX,
	PYSCR_INDIC_DASH = INDIC_DASH,
	PYSCR_INDIC_DOTS = INDIC_DOTS,
	PYSCR_INDIC_SQUIGGLELOW = INDIC_SQUIGGLELOW,
	PYSCR_INDIC_DOTBOX = INDIC_DOTBOX,
	PYSCR_INDIC_SQUIGGLEPIXMAP = INDIC_SQUIGGLEPIXMAP,
	PYSCR_INDIC_COMPOSITIONTHICK = INDIC_COMPOSITIONTHICK,
	PYSCR_INDIC_COMPOSITIONTHIN = INDIC_COMPOSITIONTHIN,
	PYSCR_INDIC_FULLBOX = INDIC_FULLBOX,
	PYSCR_INDIC_TEXTFORE = INDIC_TEXTFORE,
	PYSCR_INDIC_POINT = INDIC_POINT,
	PYSCR_INDIC_POINTCHARACTER = INDIC_POINTCHARACTER,
	PYSCR_INDIC_GRADIENT = INDIC_GRADIENT,
	PYSCR_INDIC_GRADIENTCENTRE = INDIC_GRADIENTCENTRE,
	PYSCR_INDIC_CONTAINER = INDIC_CONTAINER,
	PYSCR_INDIC_IME = INDIC_IME,
	PYSCR_INDIC_IME_MAX = INDIC_IME_MAX,
	PYSCR_INDIC_MAX = INDIC_MAX
};

enum IndicatorNumbers
{
	PYSCR_INDICATOR_CONTAINER = INDICATOR_CONTAINER,
	PYSCR_INDICATOR_IME = INDICATOR_IME,
	PYSCR_INDICATOR_IME_MAX = INDICATOR_IME_MAX,
	PYSCR_INDICATOR_MAX = INDICATOR_MAX
};

enum IndicValue
{
	PYSCR_SC_INDICVALUEBIT = SC_INDICVALUEBIT,
	PYSCR_SC_INDICVALUEMASK = SC_INDICVALUEMASK
};

enum IndicFlag
{
	PYSCR_SC_INDICFLAG_NONE = SC_INDICFLAG_NONE,
	PYSCR_SC_INDICFLAG_VALUEFORE = SC_INDICFLAG_VALUEFORE
};

enum AutoCompleteOption
{
	PYSCR_SC_AUTOCOMPLETE_NORMAL = SC_AUTOCOMPLETE_NORMAL,
	PYSCR_SC_AUTOCOMPLETE_FIXED_SIZE = SC_AUTOCOMPLETE_FIXED_SIZE
};

enum IndentView
{
	PYSCR_SC_IV_NONE = SC_IV_NONE,
	PYSCR_SC_IV_REAL = SC_IV_REAL,
	PYSCR_SC_IV_LOOKFORWARD = SC_IV_LOOKFORWARD,
	PYSCR_SC_IV_LOOKBOTH = SC_IV_LOOKBOTH
};

enum PrintOption
{
	PYSCR_SC_PRINT_NORMAL = SC_PRINT_NORMAL,
	PYSCR_SC_PRINT_INVERTLIGHT = SC_PRINT_INVERTLIGHT,
	PYSCR_SC_PRINT_BLACKONWHITE = SC_PRINT_BLACKONWHITE,
	PYSCR_SC_PRINT_COLOURONWHITE = SC_PRINT_COLOURONWHITE,
	PYSCR_SC_PRINT_COLOURONWHITEDEFAULTBG = SC_PRINT_COLOURONWHITEDEFAULTBG,
	PYSCR_SC_PRINT_SCREENCOLOURS = SC_PRINT_SCREENCOLOURS
};

enum FindOption
{
	PYSCR_SCFIND_NONE = SCFIND_NONE,
	PYSCR_SCFIND_WHOLEWORD = SCFIND_WHOLEWORD,
	PYSCR_SCFIND_MATCHCASE = SCFIND_MATCHCASE,
	PYSCR_SCFIND_WORDSTART = SCFIND_WORDSTART,
	PYSCR_SCFIND_REGEXP = SCFIND_REGEXP,
	PYSCR_SCFIND_POSIX = SCFIND_POSIX,
	PYSCR_SCFIND_CXX11REGEX = SCFIND_CXX11REGEX
};

enum FoldLevel
{
	PYSCR_SC_FOLDLEVELNONE = SC_FOLDLEVELNONE,
	PYSCR_SC_FOLDLEVELBASE = SC_FOLDLEVELBASE,
	PYSCR_SC_FOLDLEVELWHITEFLAG = SC_FOLDLEVELWHITEFLAG,
	PYSCR_SC_FOLDLEVELHEADERFLAG = SC_FOLDLEVELHEADERFLAG,
	PYSCR_SC_FOLDLEVELNUMBERMASK = SC_FOLDLEVELNUMBERMASK
};

enum FoldDisplayTextStyle
{
	PYSCR_SC_FOLDDISPLAYTEXT_HIDDEN = SC_FOLDDISPLAYTEXT_HIDDEN,
	PYSCR_SC_FOLDDISPLAYTEXT_STANDARD = SC_FOLDDISPLAYTEXT_STANDARD,
	PYSCR_SC_FOLDDISPLAYTEXT_BOXED = SC_FOLDDISPLAYTEXT_BOXED
};

enum FoldAction
{
	PYSCR_SC_FOLDACTION_CONTRACT = SC_FOLDACTION_CONTRACT,
	PYSCR_SC_FOLDACTION_EXPAND = SC_FOLDACTION_EXPAND,
	PYSCR_SC_FOLDACTION_TOGGLE = SC_FOLDACTION_TOGGLE
};

enum AutomaticFold
{
	PYSCR_SC_AUTOMATICFOLD_NONE = SC_AUTOMATICFOLD_NONE,
	PYSCR_SC_AUTOMATICFOLD_SHOW = SC_AUTOMATICFOLD_SHOW,
	PYSCR_SC_AUTOMATICFOLD_CLICK = SC_AUTOMATICFOLD_CLICK,
	PYSCR_SC_AUTOMATICFOLD_CHANGE = SC_AUTOMATICFOLD_CHANGE
};

enum FoldFlag
{
	PYSCR_SC_FOLDFLAG_NONE = SC_FOLDFLAG_NONE,
	PYSCR_SC_FOLDFLAG_LINEBEFORE_EXPANDED = SC_FOLDFLAG_LINEBEFORE_EXPANDED,
	PYSCR_SC_FOLDFLAG_LINEBEFORE_CONTRACTED = SC_FOLDFLAG_LINEBEFORE_CONTRACTED,
	PYSCR_SC_FOLDFLAG_LINEAFTER_EXPANDED = SC_FOLDFLAG_LINEAFTER_EXPANDED,
	PYSCR_SC_FOLDFLAG_LINEAFTER_CONTRACTED = SC_FOLDFLAG_LINEAFTER_CONTRACTED,
	PYSCR_SC_FOLDFLAG_LEVELNUMBERS = SC_FOLDFLAG_LEVELNUMBERS,
	PYSCR_SC_FOLDFLAG_LINESTATE = SC_FOLDFLAG_LINESTATE
};

enum IdleStyling
{
	PYSCR_SC_IDLESTYLING_NONE = SC_IDLESTYLING_NONE,
	PYSCR_SC_IDLESTYLING_TOVISIBLE = SC_IDLESTYLING_TOVISIBLE,
	PYSCR_SC_IDLESTYLING_AFTERVISIBLE = SC_IDLESTYLING_AFTERVISIBLE,
	PYSCR_SC_IDLESTYLING_ALL = SC_IDLESTYLING_ALL
};

enum Wrap
{
	PYSCR_SC_WRAP_NONE = SC_WRAP_NONE,
	PYSCR_SC_WRAP_WORD = SC_WRAP_WORD,
	PYSCR_SC_WRAP_CHAR = SC_WRAP_CHAR,
	PYSCR_SC_WRAP_WHITESPACE = SC_WRAP_WHITESPACE
};

enum WrapVisualFlag
{
	PYSCR_SC_WRAPVISUALFLAG_NONE = SC_WRAPVISUALFLAG_NONE,
	PYSCR_SC_WRAPVISUALFLAG_END = SC_WRAPVISUALFLAG_END,
	PYSCR_SC_WRAPVISUALFLAG_START = SC_WRAPVISUALFLAG_START,
	PYSCR_SC_WRAPVISUALFLAG_MARGIN = SC_WRAPVISUALFLAG_MARGIN
};

enum WrapVisualLocation
{
	PYSCR_SC_WRAPVISUALFLAGLOC_DEFAULT = SC_WRAPVISUALFLAGLOC_DEFAULT,
	PYSCR_SC_WRAPVISUALFLAGLOC_END_BY_TEXT = SC_WRAPVISUALFLAGLOC_END_BY_TEXT,
	PYSCR_SC_WRAPVISUALFLAGLOC_START_BY_TEXT = SC_WRAPVISUALFLAGLOC_START_BY_TEXT
};

enum WrapIndentMode
{
	PYSCR_SC_WRAPINDENT_FIXED = SC_WRAPINDENT_FIXED,
	PYSCR_SC_WRAPINDENT_SAME = SC_WRAPINDENT_SAME,
	PYSCR_SC_WRAPINDENT_INDENT = SC_WRAPINDENT_INDENT,
	PYSCR_SC_WRAPINDENT_DEEPINDENT = SC_WRAPINDENT_DEEPINDENT
};

enum LineCache
{
	PYSCR_SC_CACHE_NONE = SC_CACHE_NONE,
	PYSCR_SC_CACHE_CARET = SC_CACHE_CARET,
	PYSCR_SC_CACHE_PAGE = SC_CACHE_PAGE,
	PYSCR_SC_CACHE_DOCUMENT = SC_CACHE_DOCUMENT
};

enum PhasesDraw
{
	PYSCR_SC_PHASES_ONE = SC_PHASES_ONE,
	PYSCR_SC_PHASES_TWO = SC_PHASES_TWO,
	PYSCR_SC_PHASES_MULTIPLE = SC_PHASES_MULTIPLE
};

enum FontQuality
{
	PYSCR_SC_EFF_QUALITY_MASK = SC_EFF_QUALITY_MASK,
	PYSCR_SC_EFF_QUALITY_DEFAULT = SC_EFF_QUALITY_DEFAULT,
	PYSCR_SC_EFF_QUALITY_NON_ANTIALIASED = SC_EFF_QUALITY_NON_ANTIALIASED,
	PYSCR_SC_EFF_QUALITY_ANTIALIASED = SC_EFF_QUALITY_ANTIALIASED,
	PYSCR_SC_EFF_QUALITY_LCD_OPTIMIZED = SC_EFF_QUALITY_LCD_OPTIMIZED
};

enum MultiPaste
{
	PYSCR_SC_MULTIPASTE_ONCE = SC_MULTIPASTE_ONCE,
	PYSCR_SC_MULTIPASTE_EACH = SC_MULTIPASTE_EACH
};

enum Accessibility
{
	PYSCR_SC_ACCESSIBILITY_DISABLED = SC_ACCESSIBILITY_DISABLED,
	PYSCR_SC_ACCESSIBILITY_ENABLED = SC_ACCESSIBILITY_ENABLED
};

enum EdgeVisualStyle
{
	PYSCR_EDGE_NONE = EDGE_NONE,
	PYSCR_EDGE_LINE = EDGE_LINE,
	PYSCR_EDGE_BACKGROUND = EDGE_BACKGROUND,
	PYSCR_EDGE_MULTILINE = EDGE_MULTILINE
};

enum PopUp
{
	PYSCR_SC_POPUP_NEVER = SC_POPUP_NEVER,
	PYSCR_SC_POPUP_ALL = SC_POPUP_ALL,
	PYSCR_SC_POPUP_TEXT = SC_POPUP_TEXT
};

enum DocumentOption
{
	PYSCR_SC_DOCUMENTOPTION_DEFAULT = SC_DOCUMENTOPTION_DEFAULT,
	PYSCR_SC_DOCUMENTOPTION_STYLES_NONE = SC_DOCUMENTOPTION_STYLES_NONE,
	PYSCR_SC_DOCUMENTOPTION_TEXT_LARGE = SC_DOCUMENTOPTION_TEXT_LARGE
};

enum Status
{
	PYSCR_SC_STATUS_OK = SC_STATUS_OK,
	PYSCR_SC_STATUS_FAILURE = SC_STATUS_FAILURE,
	PYSCR_SC_STATUS_BADALLOC = SC_STATUS_BADALLOC,
	PYSCR_SC_STATUS_WARN_START = SC_STATUS_WARN_START,
	PYSCR_SC_STATUS_WARN_REGEX = SC_STATUS_WARN_REGEX
};

enum VisiblePolicy
{
	PYSCR_VISIBLE_SLOP = VISIBLE_SLOP,
	PYSCR_VISIBLE_STRICT = VISIBLE_STRICT
};

enum CaretPolicy
{
	PYSCR_CARET_SLOP = CARET_SLOP,
	PYSCR_CARET_STRICT = CARET_STRICT,
	PYSCR_CARET_JUMPS = CARET_JUMPS,
	PYSCR_CARET_EVEN = CARET_EVEN
};

enum SelectionMode
{
	PYSCR_SC_SEL_STREAM = SC_SEL_STREAM,
	PYSCR_SC_SEL_RECTANGLE = SC_SEL_RECTANGLE,
	PYSCR_SC_SEL_LINES = SC_SEL_LINES,
	PYSCR_SC_SEL_THIN = SC_SEL_THIN
};

enum CaseInsensitiveBehaviour
{
	PYSCR_SC_CASEINSENSITIVEBEHAVIOUR_RESPECTCASE = SC_CASEINSENSITIVEBEHAVIOUR_RESPECTCASE,
	PYSCR_SC_CASEINSENSITIVEBEHAVIOUR_IGNORECASE = SC_CASEINSENSITIVEBEHAVIOUR_IGNORECASE
};

enum MultiAutoComplete
{
	PYSCR_SC_MULTIAUTOC_ONCE = SC_MULTIAUTOC_ONCE,
	PYSCR_SC_MULTIAUTOC_EACH = SC_MULTIAUTOC_EACH
};

enum Ordering
{
	PYSCR_SC_ORDER_PRESORTED = SC_ORDER_PRESORTED,
	PYSCR_SC_ORDER_PERFORMSORT = SC_ORDER_PERFORMSORT,
	PYSCR_SC_ORDER_CUSTOM = SC_ORDER_CUSTOM
};

enum CaretSticky
{
	PYSCR_SC_CARETSTICKY_OFF = SC_CARETSTICKY_OFF,
	PYSCR_SC_CARETSTICKY_ON = SC_CARETSTICKY_ON,
	PYSCR_SC_CARETSTICKY_WHITESPACE = SC_CARETSTICKY_WHITESPACE
};

enum CaretStyle
{
	PYSCR_CARETSTYLE_INVISIBLE = CARETSTYLE_INVISIBLE,
	PYSCR_CARETSTYLE_LINE = CARETSTYLE_LINE,
	PYSCR_CARETSTYLE_BLOCK = CARETSTYLE_BLOCK,
	PYSCR_CARETSTYLE_OVERSTRIKE_BAR = CARETSTYLE_OVERSTRIKE_BAR,
	PYSCR_CARETSTYLE_OVERSTRIKE_BLOCK = CARETSTYLE_OVERSTRIKE_BLOCK,
	PYSCR_CARETSTYLE_CURSES = CARETSTYLE_CURSES,
	PYSCR_CARETSTYLE_INS_MASK = CARETSTYLE_INS_MASK,
	PYSCR_CARETSTYLE_BLOCK_AFTER = CARETSTYLE_BLOCK_AFTER
};

enum MarginOption
{
	PYSCR_SC_MARGINOPTION_NONE = SC_MARGINOPTION_NONE,
	PYSCR_SC_MARGINOPTION_SUBLINESELECT = SC_MARGINOPTION_SUBLINESELECT
};

enum AnnotationVisible
{
	PYSCR_ANNOTATION_HIDDEN = ANNOTATION_HIDDEN,
	PYSCR_ANNOTATION_STANDARD = ANNOTATION_STANDARD,
	PYSCR_ANNOTATION_BOXED = ANNOTATION_BOXED,
	PYSCR_ANNOTATION_INDENTED = ANNOTATION_INDENTED
};

enum UndoFlags
{
	PYSCR_UNDO_NONE = UNDO_NONE,
	PYSCR_UNDO_MAY_COALESCE = UNDO_MAY_COALESCE
};

enum VirtualSpace
{
	PYSCR_SCVS_NONE = SCVS_NONE,
	PYSCR_SCVS_RECTANGULARSELECTION = SCVS_RECTANGULARSELECTION,
	PYSCR_SCVS_USERACCESSIBLE = SCVS_USERACCESSIBLE,
	PYSCR_SCVS_NOWRAPLINESTART = SCVS_NOWRAPLINESTART
};

enum Technology
{
	PYSCR_SC_TECHNOLOGY_DEFAULT = SC_TECHNOLOGY_DEFAULT,
	PYSCR_SC_TECHNOLOGY_DIRECTWRITE = SC_TECHNOLOGY_DIRECTWRITE,
	PYSCR_SC_TECHNOLOGY_DIRECTWRITERETAIN = SC_TECHNOLOGY_DIRECTWRITERETAIN,
	PYSCR_SC_TECHNOLOGY_DIRECTWRITEDC = SC_TECHNOLOGY_DIRECTWRITEDC
};

enum LineEndType
{
	PYSCR_SC_LINE_END_TYPE_DEFAULT = SC_LINE_END_TYPE_DEFAULT,
	PYSCR_SC_LINE_END_TYPE_UNICODE = SC_LINE_END_TYPE_UNICODE
};

enum RepresentationAppearance
{
	PYSCR_SC_REPRESENTATION_PLAIN = SC_REPRESENTATION_PLAIN,
	PYSCR_SC_REPRESENTATION_BLOB = SC_REPRESENTATION_BLOB,
	PYSCR_SC_REPRESENTATION_COLOUR = SC_REPRESENTATION_COLOUR
};

enum EOLAnnotationVisible
{
	PYSCR_EOLANNOTATION_HIDDEN = EOLANNOTATION_HIDDEN,
	PYSCR_EOLANNOTATION_STANDARD = EOLANNOTATION_STANDARD,
	PYSCR_EOLANNOTATION_BOXED = EOLANNOTATION_BOXED,
	PYSCR_EOLANNOTATION_STADIUM = EOLANNOTATION_STADIUM,
	PYSCR_EOLANNOTATION_FLAT_CIRCLE = EOLANNOTATION_FLAT_CIRCLE,
	PYSCR_EOLANNOTATION_ANGLE_CIRCLE = EOLANNOTATION_ANGLE_CIRCLE,
	PYSCR_EOLANNOTATION_CIRCLE_FLAT = EOLANNOTATION_CIRCLE_FLAT,
	PYSCR_EOLANNOTATION_FLATS = EOLANNOTATION_FLATS,
	PYSCR_EOLANNOTATION_ANGLE_FLAT = EOLANNOTATION_ANGLE_FLAT,
	PYSCR_EOLANNOTATION_CIRCLE_ANGLE = EOLANNOTATION_CIRCLE_ANGLE,
	PYSCR_EOLANNOTATION_FLAT_ANGLE = EOLANNOTATION_FLAT_ANGLE,
	PYSCR_EOLANNOTATION_ANGLES = EOLANNOTATION_ANGLES
};

enum Supports
{
	PYSCR_SC_SUPPORTS_LINE_DRAWS_FINAL = SC_SUPPORTS_LINE_DRAWS_FINAL,
	PYSCR_SC_SUPPORTS_PIXEL_DIVISIONS = SC_SUPPORTS_PIXEL_DIVISIONS,
	PYSCR_SC_SUPPORTS_FRACTIONAL_STROKE_WIDTH = SC_SUPPORTS_FRACTIONAL_STROKE_WIDTH,
	PYSCR_SC_SUPPORTS_TRANSLUCENT_STROKE = SC_SUPPORTS_TRANSLUCENT_STROKE,
	PYSCR_SC_SUPPORTS_PIXEL_MODIFICATION = SC_SUPPORTS_PIXEL_MODIFICATION,
	PYSCR_SC_SUPPORTS_THREAD_SAFE_MEASURE_WIDTHS = SC_SUPPORTS_THREAD_SAFE_MEASURE_WIDTHS
};

enum LineCharacterIndexType
{
	PYSCR_SC_LINECHARACTERINDEX_NONE = SC_LINECHARACTERINDEX_NONE,
	PYSCR_SC_LINECHARACTERINDEX_UTF32 = SC_LINECHARACTERINDEX_UTF32,
	PYSCR_SC_LINECHARACTERINDEX_UTF16 = SC_LINECHARACTERINDEX_UTF16
};

enum TypeProperty
{
	PYSCR_SC_TYPE_BOOLEAN = SC_TYPE_BOOLEAN,
	PYSCR_SC_TYPE_INTEGER = SC_TYPE_INTEGER,
	PYSCR_SC_TYPE_STRING = SC_TYPE_STRING
};

enum ModificationFlags
{
	PYSCR_SC_MOD_NONE = SC_MOD_NONE,
	PYSCR_SC_MOD_INSERTTEXT = SC_MOD_INSERTTEXT,
	PYSCR_SC_MOD_DELETETEXT = SC_MOD_DELETETEXT,
	PYSCR_SC_MOD_CHANGESTYLE = SC_MOD_CHANGESTYLE,
	PYSCR_SC_MOD_CHANGEFOLD = SC_MOD_CHANGEFOLD,
	PYSCR_SC_PERFORMED_USER = SC_PERFORMED_USER,
	PYSCR_SC_PERFORMED_UNDO = SC_PERFORMED_UNDO,
	PYSCR_SC_PERFORMED_REDO = SC_PERFORMED_REDO,
	PYSCR_SC_MULTISTEPUNDOREDO = SC_MULTISTEPUNDOREDO,
	PYSCR_SC_LASTSTEPINUNDOREDO = SC_LASTSTEPINUNDOREDO,
	PYSCR_SC_MOD_CHANGEMARKER = SC_MOD_CHANGEMARKER,
	PYSCR_SC_MOD_BEFOREINSERT = SC_MOD_BEFOREINSERT,
	PYSCR_SC_MOD_BEFOREDELETE = SC_MOD_BEFOREDELETE,
	PYSCR_SC_MULTILINEUNDOREDO = SC_MULTILINEUNDOREDO,
	PYSCR_SC_STARTACTION = SC_STARTACTION,
	PYSCR_SC_MOD_CHANGEINDICATOR = SC_MOD_CHANGEINDICATOR,
	PYSCR_SC_MOD_CHANGELINESTATE = SC_MOD_CHANGELINESTATE,
	PYSCR_SC_MOD_CHANGEMARGIN = SC_MOD_CHANGEMARGIN,
	PYSCR_SC_MOD_CHANGEANNOTATION = SC_MOD_CHANGEANNOTATION,
	PYSCR_SC_MOD_CONTAINER = SC_MOD_CONTAINER,
	PYSCR_SC_MOD_LEXERSTATE = SC_MOD_LEXERSTATE,
	PYSCR_SC_MOD_INSERTCHECK = SC_MOD_INSERTCHECK,
	PYSCR_SC_MOD_CHANGETABSTOPS = SC_MOD_CHANGETABSTOPS,
	PYSCR_SC_MOD_CHANGEEOLANNOTATION = SC_MOD_CHANGEEOLANNOTATION,
	PYSCR_SC_MODEVENTMASKALL = SC_MODEVENTMASKALL
};

enum Update
{
	PYSCR_SC_UPDATE_NONE = SC_UPDATE_NONE,
	PYSCR_SC_UPDATE_CONTENT = SC_UPDATE_CONTENT,
	PYSCR_SC_UPDATE_SELECTION = SC_UPDATE_SELECTION,
	PYSCR_SC_UPDATE_V_SCROLL = SC_UPDATE_V_SCROLL,
	PYSCR_SC_UPDATE_H_SCROLL = SC_UPDATE_H_SCROLL
};

enum FocusChange
{
	PYSCR_SCEN_CHANGE = SCEN_CHANGE,
	PYSCR_SCEN_SETFOCUS = SCEN_SETFOCUS,
	PYSCR_SCEN_KILLFOCUS = SCEN_KILLFOCUS
};

enum Keys
{
	PYSCR_SCK_DOWN = SCK_DOWN,
	PYSCR_SCK_UP = SCK_UP,
	PYSCR_SCK_LEFT = SCK_LEFT,
	PYSCR_SCK_RIGHT = SCK_RIGHT,
	PYSCR_SCK_HOME = SCK_HOME,
	PYSCR_SCK_END = SCK_END,
	PYSCR_SCK_PRIOR = SCK_PRIOR,
	PYSCR_SCK_NEXT = SCK_NEXT,
	PYSCR_SCK_DELETE = SCK_DELETE,
	PYSCR_SCK_INSERT = SCK_INSERT,
	PYSCR_SCK_ESCAPE = SCK_ESCAPE,
	PYSCR_SCK_BACK = SCK_BACK,
	PYSCR_SCK_TAB = SCK_TAB,
	PYSCR_SCK_RETURN = SCK_RETURN,
	PYSCR_SCK_ADD = SCK_ADD,
	PYSCR_SCK_SUBTRACT = SCK_SUBTRACT,
	PYSCR_SCK_DIVIDE = SCK_DIVIDE,
	PYSCR_SCK_WIN = SCK_WIN,
	PYSCR_SCK_RWIN = SCK_RWIN,
	PYSCR_SCK_MENU = SCK_MENU
};

enum KeyMod
{
	PYSCR_SCMOD_NORM = SCMOD_NORM,
	PYSCR_SCMOD_SHIFT = SCMOD_SHIFT,
	PYSCR_SCMOD_CTRL = SCMOD_CTRL,
	PYSCR_SCMOD_ALT = SCMOD_ALT,
	PYSCR_SCMOD_SUPER = SCMOD_SUPER,
	PYSCR_SCMOD_META = SCMOD_META
};

enum CompletionMethods
{
	PYSCR_SC_AC_FILLUP = SC_AC_FILLUP,
	PYSCR_SC_AC_DOUBLECLICK = SC_AC_DOUBLECLICK,
	PYSCR_SC_AC_TAB = SC_AC_TAB,
	PYSCR_SC_AC_NEWLINE = SC_AC_NEWLINE,
	PYSCR_SC_AC_COMMAND = SC_AC_COMMAND
};

enum CharacterSource
{
	PYSCR_SC_CHARACTERSOURCE_DIRECT_INPUT = SC_CHARACTERSOURCE_DIRECT_INPUT,
	PYSCR_SC_CHARACTERSOURCE_TENTATIVE_INPUT = SC_CHARACTERSOURCE_TENTATIVE_INPUT,
	PYSCR_SC_CHARACTERSOURCE_IME_RESULT = SC_CHARACTERSOURCE_IME_RESULT
};

enum Bidirectional
{
	PYSCR_SC_BIDIRECTIONAL_DISABLED = SC_BIDIRECTIONAL_DISABLED,
	PYSCR_SC_BIDIRECTIONAL_L2R = SC_BIDIRECTIONAL_L2R,
	PYSCR_SC_BIDIRECTIONAL_R2L = SC_BIDIRECTIONAL_R2L
};

enum Lexer
{
	PYSCR_SCLEX_CONTAINER = SCLEX_CONTAINER,
	PYSCR_SCLEX_NULL = SCLEX_NULL,
	PYSCR_SCLEX_PYTHON = SCLEX_PYTHON,
	PYSCR_SCLEX_CPP = SCLEX_CPP,
	PYSCR_SCLEX_HTML = SCLEX_HTML,
	PYSCR_SCLEX_XML = SCLEX_XML,
	PYSCR_SCLEX_PERL = SCLEX_PERL,
	PYSCR_SCLEX_SQL = SCLEX_SQL,
	PYSCR_SCLEX_VB = SCLEX_VB,
	PYSCR_SCLEX_PROPERTIES = SCLEX_PROPERTIES,
	PYSCR_SCLEX_ERRORLIST = SCLEX_ERRORLIST,
	PYSCR_SCLEX_MAKEFILE = SCLEX_MAKEFILE,
	PYSCR_SCLEX_BATCH = SCLEX_BATCH,
	PYSCR_SCLEX_XCODE = SCLEX_XCODE,
	PYSCR_SCLEX_LATEX = SCLEX_LATEX,
	PYSCR_SCLEX_LUA = SCLEX_LUA,
	PYSCR_SCLEX_DIFF = SCLEX_DIFF,
	PYSCR_SCLEX_CONF = SCLEX_CONF,
	PYSCR_SCLEX_PASCAL = SCLEX_PASCAL,
	PYSCR_SCLEX_AVE = SCLEX_AVE,
	PYSCR_SCLEX_ADA = SCLEX_ADA,
	PYSCR_SCLEX_LISP = SCLEX_LISP,
	PYSCR_SCLEX_RUBY = SCLEX_RUBY,
	PYSCR_SCLEX_EIFFEL = SCLEX_EIFFEL,
	PYSCR_SCLEX_EIFFELKW = SCLEX_EIFFELKW,
	PYSCR_SCLEX_TCL = SCLEX_TCL,
	PYSCR_SCLEX_NNCRONTAB = SCLEX_NNCRONTAB,
	PYSCR_SCLEX_BULLANT = SCLEX_BULLANT,
	PYSCR_SCLEX_VBSCRIPT = SCLEX_VBSCRIPT,
	PYSCR_SCLEX_BAAN = SCLEX_BAAN,
	PYSCR_SCLEX_MATLAB = SCLEX_MATLAB,
	PYSCR_SCLEX_SCRIPTOL = SCLEX_SCRIPTOL,
	PYSCR_SCLEX_ASM = SCLEX_ASM,
	PYSCR_SCLEX_CPPNOCASE = SCLEX_CPPNOCASE,
	PYSCR_SCLEX_FORTRAN = SCLEX_FORTRAN,
	PYSCR_SCLEX_F77 = SCLEX_F77,
	PYSCR_SCLEX_CSS = SCLEX_CSS,
	PYSCR_SCLEX_POV = SCLEX_POV,
	PYSCR_SCLEX_LOUT = SCLEX_LOUT,
	PYSCR_SCLEX_ESCRIPT = SCLEX_ESCRIPT,
	PYSCR_SCLEX_PS = SCLEX_PS,
	PYSCR_SCLEX_NSIS = SCLEX_NSIS,
	PYSCR_SCLEX_MMIXAL = SCLEX_MMIXAL,
	PYSCR_SCLEX_CLW = SCLEX_CLW,
	PYSCR_SCLEX_CLWNOCASE = SCLEX_CLWNOCASE,
	PYSCR_SCLEX_LOT = SCLEX_LOT,
	PYSCR_SCLEX_YAML = SCLEX_YAML,
	PYSCR_SCLEX_TEX = SCLEX_TEX,
	PYSCR_SCLEX_METAPOST = SCLEX_METAPOST,
	PYSCR_SCLEX_POWERBASIC = SCLEX_POWERBASIC,
	PYSCR_SCLEX_FORTH = SCLEX_FORTH,
	PYSCR_SCLEX_ERLANG = SCLEX_ERLANG,
	PYSCR_SCLEX_OCTAVE = SCLEX_OCTAVE,
	PYSCR_SCLEX_MSSQL = SCLEX_MSSQL,
	PYSCR_SCLEX_VERILOG = SCLEX_VERILOG,
	PYSCR_SCLEX_KIX = SCLEX_KIX,
	PYSCR_SCLEX_GUI4CLI = SCLEX_GUI4CLI,
	PYSCR_SCLEX_SPECMAN = SCLEX_SPECMAN,
	PYSCR_SCLEX_AU3 = SCLEX_AU3,
	PYSCR_SCLEX_APDL = SCLEX_APDL,
	PYSCR_SCLEX_BASH = SCLEX_BASH,
	PYSCR_SCLEX_ASN1 = SCLEX_ASN1,
	PYSCR_SCLEX_VHDL = SCLEX_VHDL,
	PYSCR_SCLEX_CAML = SCLEX_CAML,
	PYSCR_SCLEX_BLITZBASIC = SCLEX_BLITZBASIC,
	PYSCR_SCLEX_PUREBASIC = SCLEX_PUREBASIC,
	PYSCR_SCLEX_HASKELL = SCLEX_HASKELL,
	PYSCR_SCLEX_PHPSCRIPT = SCLEX_PHPSCRIPT,
	PYSCR_SCLEX_TADS3 = SCLEX_TADS3,
	PYSCR_SCLEX_REBOL = SCLEX_REBOL,
	PYSCR_SCLEX_SMALLTALK = SCLEX_SMALLTALK,
	PYSCR_SCLEX_FLAGSHIP = SCLEX_FLAGSHIP,
	PYSCR_SCLEX_CSOUND = SCLEX_CSOUND,
	PYSCR_SCLEX_FREEBASIC = SCLEX_FREEBASIC,
	PYSCR_SCLEX_INNOSETUP = SCLEX_INNOSETUP,
	PYSCR_SCLEX_OPAL = SCLEX_OPAL,
	PYSCR_SCLEX_SPICE = SCLEX_SPICE,
	PYSCR_SCLEX_D = SCLEX_D,
	PYSCR_SCLEX_CMAKE = SCLEX_CMAKE,
	PYSCR_SCLEX_GAP = SCLEX_GAP,
	PYSCR_SCLEX_PLM = SCLEX_PLM,
	PYSCR_SCLEX_PROGRESS = SCLEX_PROGRESS,
	PYSCR_SCLEX_ABAQUS = SCLEX_ABAQUS,
	PYSCR_SCLEX_ASYMPTOTE = SCLEX_ASYMPTOTE,
	PYSCR_SCLEX_R = SCLEX_R,
	PYSCR_SCLEX_MAGIK = SCLEX_MAGIK,
	PYSCR_SCLEX_POWERSHELL = SCLEX_POWERSHELL,
	PYSCR_SCLEX_MYSQL = SCLEX_MYSQL,
	PYSCR_SCLEX_PO = SCLEX_PO,
	PYSCR_SCLEX_TAL = SCLEX_TAL,
	PYSCR_SCLEX_COBOL = SCLEX_COBOL,
	PYSCR_SCLEX_TACL = SCLEX_TACL,
	PYSCR_SCLEX_SORCUS = SCLEX_SORCUS,
	PYSCR_SCLEX_POWERPRO = SCLEX_POWERPRO,
	PYSCR_SCLEX_NIMROD = SCLEX_NIMROD,
	PYSCR_SCLEX_SML = SCLEX_SML,
	PYSCR_SCLEX_MARKDOWN = SCLEX_MARKDOWN,
	PYSCR_SCLEX_TXT2TAGS = SCLEX_TXT2TAGS,
	PYSCR_SCLEX_A68K = SCLEX_A68K,
	PYSCR_SCLEX_MODULA = SCLEX_MODULA,
	PYSCR_SCLEX_COFFEESCRIPT = SCLEX_COFFEESCRIPT,
	PYSCR_SCLEX_TCMD = SCLEX_TCMD,
	PYSCR_SCLEX_AVS = SCLEX_AVS,
	PYSCR_SCLEX_ECL = SCLEX_ECL,
	PYSCR_SCLEX_OSCRIPT = SCLEX_OSCRIPT,
	PYSCR_SCLEX_VISUALPROLOG = SCLEX_VISUALPROLOG,
	PYSCR_SCLEX_LITERATEHASKELL = SCLEX_LITERATEHASKELL,
	PYSCR_SCLEX_STTXT = SCLEX_STTXT,
	PYSCR_SCLEX_KVIRC = SCLEX_KVIRC,
	PYSCR_SCLEX_RUST = SCLEX_RUST,
	PYSCR_SCLEX_DMAP = SCLEX_DMAP,
	PYSCR_SCLEX_AS = SCLEX_AS,
	PYSCR_SCLEX_DMIS = SCLEX_DMIS,
	PYSCR_SCLEX_REGISTRY = SCLEX_REGISTRY,
	PYSCR_SCLEX_BIBTEX = SCLEX_BIBTEX,
	PYSCR_SCLEX_SREC = SCLEX_SREC,
	PYSCR_SCLEX_IHEX = SCLEX_IHEX,
	PYSCR_SCLEX_TEHEX = SCLEX_TEHEX,
	PYSCR_SCLEX_JSON = SCLEX_JSON,
	PYSCR_SCLEX_EDIFACT = SCLEX_EDIFACT,
	PYSCR_SCLEX_INDENT = SCLEX_INDENT,
	PYSCR_SCLEX_MAXIMA = SCLEX_MAXIMA,
	PYSCR_SCLEX_STATA = SCLEX_STATA,
	PYSCR_SCLEX_SAS = SCLEX_SAS,
	PYSCR_SCLEX_NIM = SCLEX_NIM,
	PYSCR_SCLEX_CIL = SCLEX_CIL,
	PYSCR_SCLEX_X12 = SCLEX_X12,
	PYSCR_SCLEX_DATAFLEX = SCLEX_DATAFLEX,
	PYSCR_SCLEX_HOLLYWOOD = SCLEX_HOLLYWOOD,
	PYSCR_SCLEX_RAKU = SCLEX_RAKU,
	PYSCR_SCLEX_FSHARP = SCLEX_FSHARP,
	PYSCR_SCLEX_JULIA = SCLEX_JULIA,
	PYSCR_SCLEX_ASCIIDOC = SCLEX_ASCIIDOC,
	PYSCR_SCLEX_GDSCRIPT = SCLEX_GDSCRIPT,
	PYSCR_SCLEX_AUTOMATIC = SCLEX_AUTOMATIC
};


/* The following is the enum of events/notifications.
		   * Note that the PYSCN_XXX constants are NOT automatically generated (in ScintillaNotifications.h).
		   * This is very deliberate.
		   * An error here indicates that a new notification has been added,
		   * and hence handler code should be added to the ScintillaWrapper::notify() function
		   */
enum ScintillaMessage
{
	PYSCR_SCI_ADDTEXT = SCI_ADDTEXT,
	PYSCR_SCI_ADDSTYLEDTEXT = SCI_ADDSTYLEDTEXT,
	PYSCR_SCI_INSERTTEXT = SCI_INSERTTEXT,
	PYSCR_SCI_CHANGEINSERTION = SCI_CHANGEINSERTION,
	PYSCR_SCI_CLEARALL = SCI_CLEARALL,
	PYSCR_SCI_DELETERANGE = SCI_DELETERANGE,
	PYSCR_SCI_CLEARDOCUMENTSTYLE = SCI_CLEARDOCUMENTSTYLE,
	PYSCR_SCI_GETLENGTH = SCI_GETLENGTH,
	PYSCR_SCI_GETCHARAT = SCI_GETCHARAT,
	PYSCR_SCI_GETCURRENTPOS = SCI_GETCURRENTPOS,
	PYSCR_SCI_GETANCHOR = SCI_GETANCHOR,
	PYSCR_SCI_GETSTYLEAT = SCI_GETSTYLEAT,
	PYSCR_SCI_GETSTYLEINDEXAT = SCI_GETSTYLEINDEXAT,
	PYSCR_SCI_REDO = SCI_REDO,
	PYSCR_SCI_SETUNDOCOLLECTION = SCI_SETUNDOCOLLECTION,
	PYSCR_SCI_SELECTALL = SCI_SELECTALL,
	PYSCR_SCI_SETSAVEPOINT = SCI_SETSAVEPOINT,
	PYSCR_SCI_GETSTYLEDTEXT = SCI_GETSTYLEDTEXT,
	PYSCR_SCI_CANREDO = SCI_CANREDO,
	PYSCR_SCI_MARKERLINEFROMHANDLE = SCI_MARKERLINEFROMHANDLE,
	PYSCR_SCI_MARKERDELETEHANDLE = SCI_MARKERDELETEHANDLE,
	PYSCR_SCI_MARKERHANDLEFROMLINE = SCI_MARKERHANDLEFROMLINE,
	PYSCR_SCI_MARKERNUMBERFROMLINE = SCI_MARKERNUMBERFROMLINE,
	PYSCR_SCI_GETUNDOCOLLECTION = SCI_GETUNDOCOLLECTION,
	PYSCR_SCI_GETVIEWWS = SCI_GETVIEWWS,
	PYSCR_SCI_SETVIEWWS = SCI_SETVIEWWS,
	PYSCR_SCI_GETTABDRAWMODE = SCI_GETTABDRAWMODE,
	PYSCR_SCI_SETTABDRAWMODE = SCI_SETTABDRAWMODE,
	PYSCR_SCI_POSITIONFROMPOINT = SCI_POSITIONFROMPOINT,
	PYSCR_SCI_POSITIONFROMPOINTCLOSE = SCI_POSITIONFROMPOINTCLOSE,
	PYSCR_SCI_GOTOLINE = SCI_GOTOLINE,
	PYSCR_SCI_GOTOPOS = SCI_GOTOPOS,
	PYSCR_SCI_SETANCHOR = SCI_SETANCHOR,
	PYSCR_SCI_GETCURLINE = SCI_GETCURLINE,
	PYSCR_SCI_GETENDSTYLED = SCI_GETENDSTYLED,
	PYSCR_SCI_CONVERTEOLS = SCI_CONVERTEOLS,
	PYSCR_SCI_GETEOLMODE = SCI_GETEOLMODE,
	PYSCR_SCI_SETEOLMODE = SCI_SETEOLMODE,
	PYSCR_SCI_STARTSTYLING = SCI_STARTSTYLING,
	PYSCR_SCI_SETSTYLING = SCI_SETSTYLING,
	PYSCR_SCI_GETBUFFEREDDRAW = SCI_GETBUFFEREDDRAW,
	PYSCR_SCI_SETBUFFEREDDRAW = SCI_SETBUFFEREDDRAW,
	PYSCR_SCI_SETTABWIDTH = SCI_SETTABWIDTH,
	PYSCR_SCI_GETTABWIDTH = SCI_GETTABWIDTH,
	PYSCR_SCI_SETTABMINIMUMWIDTH = SCI_SETTABMINIMUMWIDTH,
	PYSCR_SCI_GETTABMINIMUMWIDTH = SCI_GETTABMINIMUMWIDTH,
	PYSCR_SCI_CLEARTABSTOPS = SCI_CLEARTABSTOPS,
	PYSCR_SCI_ADDTABSTOP = SCI_ADDTABSTOP,
	PYSCR_SCI_GETNEXTTABSTOP = SCI_GETNEXTTABSTOP,
	PYSCR_SCI_SETCODEPAGE = SCI_SETCODEPAGE,
	PYSCR_SCI_SETFONTLOCALE = SCI_SETFONTLOCALE,
	PYSCR_SCI_GETFONTLOCALE = SCI_GETFONTLOCALE,
	PYSCR_SCI_GETIMEINTERACTION = SCI_GETIMEINTERACTION,
	PYSCR_SCI_SETIMEINTERACTION = SCI_SETIMEINTERACTION,
	PYSCR_SCI_MARKERDEFINE = SCI_MARKERDEFINE,
	PYSCR_SCI_MARKERSETFORE = SCI_MARKERSETFORE,
	PYSCR_SCI_MARKERSETBACK = SCI_MARKERSETBACK,
	PYSCR_SCI_MARKERSETBACKSELECTED = SCI_MARKERSETBACKSELECTED,
	PYSCR_SCI_MARKERSETFORETRANSLUCENT = SCI_MARKERSETFORETRANSLUCENT,
	PYSCR_SCI_MARKERSETBACKTRANSLUCENT = SCI_MARKERSETBACKTRANSLUCENT,
	PYSCR_SCI_MARKERSETBACKSELECTEDTRANSLUCENT = SCI_MARKERSETBACKSELECTEDTRANSLUCENT,
	PYSCR_SCI_MARKERSETSTROKEWIDTH = SCI_MARKERSETSTROKEWIDTH,
	PYSCR_SCI_MARKERENABLEHIGHLIGHT = SCI_MARKERENABLEHIGHLIGHT,
	PYSCR_SCI_MARKERADD = SCI_MARKERADD,
	PYSCR_SCI_MARKERDELETE = SCI_MARKERDELETE,
	PYSCR_SCI_MARKERDELETEALL = SCI_MARKERDELETEALL,
	PYSCR_SCI_MARKERGET = SCI_MARKERGET,
	PYSCR_SCI_MARKERNEXT = SCI_MARKERNEXT,
	PYSCR_SCI_MARKERPREVIOUS = SCI_MARKERPREVIOUS,
	PYSCR_SCI_MARKERDEFINEPIXMAP = SCI_MARKERDEFINEPIXMAP,
	PYSCR_SCI_MARKERADDSET = SCI_MARKERADDSET,
	PYSCR_SCI_MARKERSETALPHA = SCI_MARKERSETALPHA,
	PYSCR_SCI_MARKERGETLAYER = SCI_MARKERGETLAYER,
	PYSCR_SCI_MARKERSETLAYER = SCI_MARKERSETLAYER,
	PYSCR_SCI_SETMARGINTYPEN = SCI_SETMARGINTYPEN,
	PYSCR_SCI_GETMARGINTYPEN = SCI_GETMARGINTYPEN,
	PYSCR_SCI_SETMARGINWIDTHN = SCI_SETMARGINWIDTHN,
	PYSCR_SCI_GETMARGINWIDTHN = SCI_GETMARGINWIDTHN,
	PYSCR_SCI_SETMARGINMASKN = SCI_SETMARGINMASKN,
	PYSCR_SCI_GETMARGINMASKN = SCI_GETMARGINMASKN,
	PYSCR_SCI_SETMARGINSENSITIVEN = SCI_SETMARGINSENSITIVEN,
	PYSCR_SCI_GETMARGINSENSITIVEN = SCI_GETMARGINSENSITIVEN,
	PYSCR_SCI_SETMARGINCURSORN = SCI_SETMARGINCURSORN,
	PYSCR_SCI_GETMARGINCURSORN = SCI_GETMARGINCURSORN,
	PYSCR_SCI_SETMARGINBACKN = SCI_SETMARGINBACKN,
	PYSCR_SCI_GETMARGINBACKN = SCI_GETMARGINBACKN,
	PYSCR_SCI_SETMARGINS = SCI_SETMARGINS,
	PYSCR_SCI_GETMARGINS = SCI_GETMARGINS,
	PYSCR_SCI_STYLECLEARALL = SCI_STYLECLEARALL,
	PYSCR_SCI_STYLESETFORE = SCI_STYLESETFORE,
	PYSCR_SCI_STYLESETBACK = SCI_STYLESETBACK,
	PYSCR_SCI_STYLESETBOLD = SCI_STYLESETBOLD,
	PYSCR_SCI_STYLESETITALIC = SCI_STYLESETITALIC,
	PYSCR_SCI_STYLESETSIZE = SCI_STYLESETSIZE,
	PYSCR_SCI_STYLESETFONT = SCI_STYLESETFONT,
	PYSCR_SCI_STYLESETEOLFILLED = SCI_STYLESETEOLFILLED,
	PYSCR_SCI_STYLERESETDEFAULT = SCI_STYLERESETDEFAULT,
	PYSCR_SCI_STYLESETUNDERLINE = SCI_STYLESETUNDERLINE,
	PYSCR_SCI_STYLEGETFORE = SCI_STYLEGETFORE,
	PYSCR_SCI_STYLEGETBACK = SCI_STYLEGETBACK,
	PYSCR_SCI_STYLEGETBOLD = SCI_STYLEGETBOLD,
	PYSCR_SCI_STYLEGETITALIC = SCI_STYLEGETITALIC,
	PYSCR_SCI_STYLEGETSIZE = SCI_STYLEGETSIZE,
	PYSCR_SCI_STYLEGETFONT = SCI_STYLEGETFONT,
	PYSCR_SCI_STYLEGETEOLFILLED = SCI_STYLEGETEOLFILLED,
	PYSCR_SCI_STYLEGETUNDERLINE = SCI_STYLEGETUNDERLINE,
	PYSCR_SCI_STYLEGETCASE = SCI_STYLEGETCASE,
	PYSCR_SCI_STYLEGETCHARACTERSET = SCI_STYLEGETCHARACTERSET,
	PYSCR_SCI_STYLEGETVISIBLE = SCI_STYLEGETVISIBLE,
	PYSCR_SCI_STYLEGETCHANGEABLE = SCI_STYLEGETCHANGEABLE,
	PYSCR_SCI_STYLEGETHOTSPOT = SCI_STYLEGETHOTSPOT,
	PYSCR_SCI_STYLESETCASE = SCI_STYLESETCASE,
	PYSCR_SCI_STYLESETSIZEFRACTIONAL = SCI_STYLESETSIZEFRACTIONAL,
	PYSCR_SCI_STYLEGETSIZEFRACTIONAL = SCI_STYLEGETSIZEFRACTIONAL,
	PYSCR_SCI_STYLESETWEIGHT = SCI_STYLESETWEIGHT,
	PYSCR_SCI_STYLEGETWEIGHT = SCI_STYLEGETWEIGHT,
	PYSCR_SCI_STYLESETCHARACTERSET = SCI_STYLESETCHARACTERSET,
	PYSCR_SCI_STYLESETHOTSPOT = SCI_STYLESETHOTSPOT,
	PYSCR_SCI_STYLESETCHECKMONOSPACED = SCI_STYLESETCHECKMONOSPACED,
	PYSCR_SCI_STYLEGETCHECKMONOSPACED = SCI_STYLEGETCHECKMONOSPACED,
	PYSCR_SCI_SETELEMENTCOLOUR = SCI_SETELEMENTCOLOUR,
	PYSCR_SCI_GETELEMENTCOLOUR = SCI_GETELEMENTCOLOUR,
	PYSCR_SCI_RESETELEMENTCOLOUR = SCI_RESETELEMENTCOLOUR,
	PYSCR_SCI_GETELEMENTISSET = SCI_GETELEMENTISSET,
	PYSCR_SCI_GETELEMENTALLOWSTRANSLUCENT = SCI_GETELEMENTALLOWSTRANSLUCENT,
	PYSCR_SCI_GETELEMENTBASECOLOUR = SCI_GETELEMENTBASECOLOUR,
	PYSCR_SCI_SETSELFORE = SCI_SETSELFORE,
	PYSCR_SCI_SETSELBACK = SCI_SETSELBACK,
	PYSCR_SCI_GETSELALPHA = SCI_GETSELALPHA,
	PYSCR_SCI_SETSELALPHA = SCI_SETSELALPHA,
	PYSCR_SCI_GETSELEOLFILLED = SCI_GETSELEOLFILLED,
	PYSCR_SCI_SETSELEOLFILLED = SCI_SETSELEOLFILLED,
	PYSCR_SCI_GETSELECTIONLAYER = SCI_GETSELECTIONLAYER,
	PYSCR_SCI_SETSELECTIONLAYER = SCI_SETSELECTIONLAYER,
	PYSCR_SCI_GETCARETLINELAYER = SCI_GETCARETLINELAYER,
	PYSCR_SCI_SETCARETLINELAYER = SCI_SETCARETLINELAYER,
	PYSCR_SCI_GETCARETLINEHIGHLIGHTSUBLINE = SCI_GETCARETLINEHIGHLIGHTSUBLINE,
	PYSCR_SCI_SETCARETLINEHIGHLIGHTSUBLINE = SCI_SETCARETLINEHIGHLIGHTSUBLINE,
	PYSCR_SCI_SETCARETFORE = SCI_SETCARETFORE,
	PYSCR_SCI_ASSIGNCMDKEY = SCI_ASSIGNCMDKEY,
	PYSCR_SCI_CLEARCMDKEY = SCI_CLEARCMDKEY,
	PYSCR_SCI_CLEARALLCMDKEYS = SCI_CLEARALLCMDKEYS,
	PYSCR_SCI_SETSTYLINGEX = SCI_SETSTYLINGEX,
	PYSCR_SCI_STYLESETVISIBLE = SCI_STYLESETVISIBLE,
	PYSCR_SCI_GETCARETPERIOD = SCI_GETCARETPERIOD,
	PYSCR_SCI_SETCARETPERIOD = SCI_SETCARETPERIOD,
	PYSCR_SCI_SETWORDCHARS = SCI_SETWORDCHARS,
	PYSCR_SCI_GETWORDCHARS = SCI_GETWORDCHARS,
	PYSCR_SCI_SETCHARACTERCATEGORYOPTIMIZATION = SCI_SETCHARACTERCATEGORYOPTIMIZATION,
	PYSCR_SCI_GETCHARACTERCATEGORYOPTIMIZATION = SCI_GETCHARACTERCATEGORYOPTIMIZATION,
	PYSCR_SCI_BEGINUNDOACTION = SCI_BEGINUNDOACTION,
	PYSCR_SCI_ENDUNDOACTION = SCI_ENDUNDOACTION,
	PYSCR_SCI_INDICSETSTYLE = SCI_INDICSETSTYLE,
	PYSCR_SCI_INDICGETSTYLE = SCI_INDICGETSTYLE,
	PYSCR_SCI_INDICSETFORE = SCI_INDICSETFORE,
	PYSCR_SCI_INDICGETFORE = SCI_INDICGETFORE,
	PYSCR_SCI_INDICSETUNDER = SCI_INDICSETUNDER,
	PYSCR_SCI_INDICGETUNDER = SCI_INDICGETUNDER,
	PYSCR_SCI_INDICSETHOVERSTYLE = SCI_INDICSETHOVERSTYLE,
	PYSCR_SCI_INDICGETHOVERSTYLE = SCI_INDICGETHOVERSTYLE,
	PYSCR_SCI_INDICSETHOVERFORE = SCI_INDICSETHOVERFORE,
	PYSCR_SCI_INDICGETHOVERFORE = SCI_INDICGETHOVERFORE,
	PYSCR_SCI_INDICSETFLAGS = SCI_INDICSETFLAGS,
	PYSCR_SCI_INDICGETFLAGS = SCI_INDICGETFLAGS,
	PYSCR_SCI_INDICSETSTROKEWIDTH = SCI_INDICSETSTROKEWIDTH,
	PYSCR_SCI_INDICGETSTROKEWIDTH = SCI_INDICGETSTROKEWIDTH,
	PYSCR_SCI_SETWHITESPACEFORE = SCI_SETWHITESPACEFORE,
	PYSCR_SCI_SETWHITESPACEBACK = SCI_SETWHITESPACEBACK,
	PYSCR_SCI_SETWHITESPACESIZE = SCI_SETWHITESPACESIZE,
	PYSCR_SCI_GETWHITESPACESIZE = SCI_GETWHITESPACESIZE,
	PYSCR_SCI_SETLINESTATE = SCI_SETLINESTATE,
	PYSCR_SCI_GETLINESTATE = SCI_GETLINESTATE,
	PYSCR_SCI_GETMAXLINESTATE = SCI_GETMAXLINESTATE,
	PYSCR_SCI_GETCARETLINEVISIBLE = SCI_GETCARETLINEVISIBLE,
	PYSCR_SCI_SETCARETLINEVISIBLE = SCI_SETCARETLINEVISIBLE,
	PYSCR_SCI_GETCARETLINEBACK = SCI_GETCARETLINEBACK,
	PYSCR_SCI_SETCARETLINEBACK = SCI_SETCARETLINEBACK,
	PYSCR_SCI_GETCARETLINEFRAME = SCI_GETCARETLINEFRAME,
	PYSCR_SCI_SETCARETLINEFRAME = SCI_SETCARETLINEFRAME,
	PYSCR_SCI_STYLESETCHANGEABLE = SCI_STYLESETCHANGEABLE,
	PYSCR_SCI_AUTOCSHOW = SCI_AUTOCSHOW,
	PYSCR_SCI_AUTOCCANCEL = SCI_AUTOCCANCEL,
	PYSCR_SCI_AUTOCACTIVE = SCI_AUTOCACTIVE,
	PYSCR_SCI_AUTOCPOSSTART = SCI_AUTOCPOSSTART,
	PYSCR_SCI_AUTOCCOMPLETE = SCI_AUTOCCOMPLETE,
	PYSCR_SCI_AUTOCSTOPS = SCI_AUTOCSTOPS,
	PYSCR_SCI_AUTOCSETSEPARATOR = SCI_AUTOCSETSEPARATOR,
	PYSCR_SCI_AUTOCGETSEPARATOR = SCI_AUTOCGETSEPARATOR,
	PYSCR_SCI_AUTOCSELECT = SCI_AUTOCSELECT,
	PYSCR_SCI_AUTOCSETCANCELATSTART = SCI_AUTOCSETCANCELATSTART,
	PYSCR_SCI_AUTOCGETCANCELATSTART = SCI_AUTOCGETCANCELATSTART,
	PYSCR_SCI_AUTOCSETFILLUPS = SCI_AUTOCSETFILLUPS,
	PYSCR_SCI_AUTOCSETCHOOSESINGLE = SCI_AUTOCSETCHOOSESINGLE,
	PYSCR_SCI_AUTOCGETCHOOSESINGLE = SCI_AUTOCGETCHOOSESINGLE,
	PYSCR_SCI_AUTOCSETIGNORECASE = SCI_AUTOCSETIGNORECASE,
	PYSCR_SCI_AUTOCGETIGNORECASE = SCI_AUTOCGETIGNORECASE,
	PYSCR_SCI_USERLISTSHOW = SCI_USERLISTSHOW,
	PYSCR_SCI_AUTOCSETAUTOHIDE = SCI_AUTOCSETAUTOHIDE,
	PYSCR_SCI_AUTOCGETAUTOHIDE = SCI_AUTOCGETAUTOHIDE,
	PYSCR_SCI_AUTOCSETOPTIONS = SCI_AUTOCSETOPTIONS,
	PYSCR_SCI_AUTOCGETOPTIONS = SCI_AUTOCGETOPTIONS,
	PYSCR_SCI_AUTOCSETDROPRESTOFWORD = SCI_AUTOCSETDROPRESTOFWORD,
	PYSCR_SCI_AUTOCGETDROPRESTOFWORD = SCI_AUTOCGETDROPRESTOFWORD,
	PYSCR_SCI_REGISTERIMAGE = SCI_REGISTERIMAGE,
	PYSCR_SCI_CLEARREGISTEREDIMAGES = SCI_CLEARREGISTEREDIMAGES,
	PYSCR_SCI_AUTOCGETTYPESEPARATOR = SCI_AUTOCGETTYPESEPARATOR,
	PYSCR_SCI_AUTOCSETTYPESEPARATOR = SCI_AUTOCSETTYPESEPARATOR,
	PYSCR_SCI_AUTOCSETMAXWIDTH = SCI_AUTOCSETMAXWIDTH,
	PYSCR_SCI_AUTOCGETMAXWIDTH = SCI_AUTOCGETMAXWIDTH,
	PYSCR_SCI_AUTOCSETMAXHEIGHT = SCI_AUTOCSETMAXHEIGHT,
	PYSCR_SCI_AUTOCGETMAXHEIGHT = SCI_AUTOCGETMAXHEIGHT,
	PYSCR_SCI_SETINDENT = SCI_SETINDENT,
	PYSCR_SCI_GETINDENT = SCI_GETINDENT,
	PYSCR_SCI_SETUSETABS = SCI_SETUSETABS,
	PYSCR_SCI_GETUSETABS = SCI_GETUSETABS,
	PYSCR_SCI_SETLINEINDENTATION = SCI_SETLINEINDENTATION,
	PYSCR_SCI_GETLINEINDENTATION = SCI_GETLINEINDENTATION,
	PYSCR_SCI_GETLINEINDENTPOSITION = SCI_GETLINEINDENTPOSITION,
	PYSCR_SCI_GETCOLUMN = SCI_GETCOLUMN,
	PYSCR_SCI_COUNTCHARACTERS = SCI_COUNTCHARACTERS,
	PYSCR_SCI_COUNTCODEUNITS = SCI_COUNTCODEUNITS,
	PYSCR_SCI_SETHSCROLLBAR = SCI_SETHSCROLLBAR,
	PYSCR_SCI_GETHSCROLLBAR = SCI_GETHSCROLLBAR,
	PYSCR_SCI_SETINDENTATIONGUIDES = SCI_SETINDENTATIONGUIDES,
	PYSCR_SCI_GETINDENTATIONGUIDES = SCI_GETINDENTATIONGUIDES,
	PYSCR_SCI_SETHIGHLIGHTGUIDE = SCI_SETHIGHLIGHTGUIDE,
	PYSCR_SCI_GETHIGHLIGHTGUIDE = SCI_GETHIGHLIGHTGUIDE,
	PYSCR_SCI_GETLINEENDPOSITION = SCI_GETLINEENDPOSITION,
	PYSCR_SCI_GETCODEPAGE = SCI_GETCODEPAGE,
	PYSCR_SCI_GETCARETFORE = SCI_GETCARETFORE,
	PYSCR_SCI_GETREADONLY = SCI_GETREADONLY,
	PYSCR_SCI_SETCURRENTPOS = SCI_SETCURRENTPOS,
	PYSCR_SCI_SETSELECTIONSTART = SCI_SETSELECTIONSTART,
	PYSCR_SCI_GETSELECTIONSTART = SCI_GETSELECTIONSTART,
	PYSCR_SCI_SETSELECTIONEND = SCI_SETSELECTIONEND,
	PYSCR_SCI_GETSELECTIONEND = SCI_GETSELECTIONEND,
	PYSCR_SCI_SETEMPTYSELECTION = SCI_SETEMPTYSELECTION,
	PYSCR_SCI_SETPRINTMAGNIFICATION = SCI_SETPRINTMAGNIFICATION,
	PYSCR_SCI_GETPRINTMAGNIFICATION = SCI_GETPRINTMAGNIFICATION,
	PYSCR_SCI_SETPRINTCOLOURMODE = SCI_SETPRINTCOLOURMODE,
	PYSCR_SCI_GETPRINTCOLOURMODE = SCI_GETPRINTCOLOURMODE,
	PYSCR_SCI_FINDTEXT = SCI_FINDTEXT,
	PYSCR_SCI_FINDTEXTFULL = SCI_FINDTEXTFULL,
	PYSCR_SCI_FORMATRANGE = SCI_FORMATRANGE,
	PYSCR_SCI_FORMATRANGEFULL = SCI_FORMATRANGEFULL,
	PYSCR_SCI_GETFIRSTVISIBLELINE = SCI_GETFIRSTVISIBLELINE,
	PYSCR_SCI_GETLINE = SCI_GETLINE,
	PYSCR_SCI_GETLINECOUNT = SCI_GETLINECOUNT,
	PYSCR_SCI_ALLOCATELINES = SCI_ALLOCATELINES,
	PYSCR_SCI_SETMARGINLEFT = SCI_SETMARGINLEFT,
	PYSCR_SCI_GETMARGINLEFT = SCI_GETMARGINLEFT,
	PYSCR_SCI_SETMARGINRIGHT = SCI_SETMARGINRIGHT,
	PYSCR_SCI_GETMARGINRIGHT = SCI_GETMARGINRIGHT,
	PYSCR_SCI_GETMODIFY = SCI_GETMODIFY,
	PYSCR_SCI_SETSEL = SCI_SETSEL,
	PYSCR_SCI_GETSELTEXT = SCI_GETSELTEXT,
	PYSCR_SCI_GETTEXTRANGE = SCI_GETTEXTRANGE,
	PYSCR_SCI_GETTEXTRANGEFULL = SCI_GETTEXTRANGEFULL,
	PYSCR_SCI_HIDESELECTION = SCI_HIDESELECTION,
	PYSCR_SCI_POINTXFROMPOSITION = SCI_POINTXFROMPOSITION,
	PYSCR_SCI_POINTYFROMPOSITION = SCI_POINTYFROMPOSITION,
	PYSCR_SCI_LINEFROMPOSITION = SCI_LINEFROMPOSITION,
	PYSCR_SCI_POSITIONFROMLINE = SCI_POSITIONFROMLINE,
	PYSCR_SCI_LINESCROLL = SCI_LINESCROLL,
	PYSCR_SCI_SCROLLCARET = SCI_SCROLLCARET,
	PYSCR_SCI_SCROLLRANGE = SCI_SCROLLRANGE,
	PYSCR_SCI_REPLACESEL = SCI_REPLACESEL,
	PYSCR_SCI_SETREADONLY = SCI_SETREADONLY,
	PYSCR_SCI_NULL = SCI_NULL,
	PYSCR_SCI_CANPASTE = SCI_CANPASTE,
	PYSCR_SCI_CANUNDO = SCI_CANUNDO,
	PYSCR_SCI_EMPTYUNDOBUFFER = SCI_EMPTYUNDOBUFFER,
	PYSCR_SCI_UNDO = SCI_UNDO,
	PYSCR_SCI_CUT = SCI_CUT,
	PYSCR_SCI_COPY = SCI_COPY,
	PYSCR_SCI_PASTE = SCI_PASTE,
	PYSCR_SCI_CLEAR = SCI_CLEAR,
	PYSCR_SCI_SETTEXT = SCI_SETTEXT,
	PYSCR_SCI_GETTEXT = SCI_GETTEXT,
	PYSCR_SCI_GETTEXTLENGTH = SCI_GETTEXTLENGTH,
	PYSCR_SCI_GETDIRECTFUNCTION = SCI_GETDIRECTFUNCTION,
	PYSCR_SCI_GETDIRECTSTATUSFUNCTION = SCI_GETDIRECTSTATUSFUNCTION,
	PYSCR_SCI_GETDIRECTPOINTER = SCI_GETDIRECTPOINTER,
	PYSCR_SCI_SETOVERTYPE = SCI_SETOVERTYPE,
	PYSCR_SCI_GETOVERTYPE = SCI_GETOVERTYPE,
	PYSCR_SCI_SETCARETWIDTH = SCI_SETCARETWIDTH,
	PYSCR_SCI_GETCARETWIDTH = SCI_GETCARETWIDTH,
	PYSCR_SCI_SETTARGETSTART = SCI_SETTARGETSTART,
	PYSCR_SCI_GETTARGETSTART = SCI_GETTARGETSTART,
	PYSCR_SCI_SETTARGETSTARTVIRTUALSPACE = SCI_SETTARGETSTARTVIRTUALSPACE,
	PYSCR_SCI_GETTARGETSTARTVIRTUALSPACE = SCI_GETTARGETSTARTVIRTUALSPACE,
	PYSCR_SCI_SETTARGETEND = SCI_SETTARGETEND,
	PYSCR_SCI_GETTARGETEND = SCI_GETTARGETEND,
	PYSCR_SCI_SETTARGETENDVIRTUALSPACE = SCI_SETTARGETENDVIRTUALSPACE,
	PYSCR_SCI_GETTARGETENDVIRTUALSPACE = SCI_GETTARGETENDVIRTUALSPACE,
	PYSCR_SCI_SETTARGETRANGE = SCI_SETTARGETRANGE,
	PYSCR_SCI_GETTARGETTEXT = SCI_GETTARGETTEXT,
	PYSCR_SCI_TARGETFROMSELECTION = SCI_TARGETFROMSELECTION,
	PYSCR_SCI_TARGETWHOLEDOCUMENT = SCI_TARGETWHOLEDOCUMENT,
	PYSCR_SCI_REPLACETARGET = SCI_REPLACETARGET,
	PYSCR_SCI_REPLACETARGETRE = SCI_REPLACETARGETRE,
	PYSCR_SCI_SEARCHINTARGET = SCI_SEARCHINTARGET,
	PYSCR_SCI_SETSEARCHFLAGS = SCI_SETSEARCHFLAGS,
	PYSCR_SCI_GETSEARCHFLAGS = SCI_GETSEARCHFLAGS,
	PYSCR_SCI_CALLTIPSHOW = SCI_CALLTIPSHOW,
	PYSCR_SCI_CALLTIPCANCEL = SCI_CALLTIPCANCEL,
	PYSCR_SCI_CALLTIPACTIVE = SCI_CALLTIPACTIVE,
	PYSCR_SCI_CALLTIPPOSSTART = SCI_CALLTIPPOSSTART,
	PYSCR_SCI_CALLTIPSETPOSSTART = SCI_CALLTIPSETPOSSTART,
	PYSCR_SCI_CALLTIPSETHLT = SCI_CALLTIPSETHLT,
	PYSCR_SCI_CALLTIPSETBACK = SCI_CALLTIPSETBACK,
	PYSCR_SCI_CALLTIPSETFORE = SCI_CALLTIPSETFORE,
	PYSCR_SCI_CALLTIPSETFOREHLT = SCI_CALLTIPSETFOREHLT,
	PYSCR_SCI_CALLTIPUSESTYLE = SCI_CALLTIPUSESTYLE,
	PYSCR_SCI_CALLTIPSETPOSITION = SCI_CALLTIPSETPOSITION,
	PYSCR_SCI_VISIBLEFROMDOCLINE = SCI_VISIBLEFROMDOCLINE,
	PYSCR_SCI_DOCLINEFROMVISIBLE = SCI_DOCLINEFROMVISIBLE,
	PYSCR_SCI_WRAPCOUNT = SCI_WRAPCOUNT,
	PYSCR_SCI_SETFOLDLEVEL = SCI_SETFOLDLEVEL,
	PYSCR_SCI_GETFOLDLEVEL = SCI_GETFOLDLEVEL,
	PYSCR_SCI_GETLASTCHILD = SCI_GETLASTCHILD,
	PYSCR_SCI_GETFOLDPARENT = SCI_GETFOLDPARENT,
	PYSCR_SCI_SHOWLINES = SCI_SHOWLINES,
	PYSCR_SCI_HIDELINES = SCI_HIDELINES,
	PYSCR_SCI_GETLINEVISIBLE = SCI_GETLINEVISIBLE,
	PYSCR_SCI_GETALLLINESVISIBLE = SCI_GETALLLINESVISIBLE,
	PYSCR_SCI_SETFOLDEXPANDED = SCI_SETFOLDEXPANDED,
	PYSCR_SCI_GETFOLDEXPANDED = SCI_GETFOLDEXPANDED,
	PYSCR_SCI_TOGGLEFOLD = SCI_TOGGLEFOLD,
	PYSCR_SCI_TOGGLEFOLDSHOWTEXT = SCI_TOGGLEFOLDSHOWTEXT,
	PYSCR_SCI_FOLDDISPLAYTEXTSETSTYLE = SCI_FOLDDISPLAYTEXTSETSTYLE,
	PYSCR_SCI_FOLDDISPLAYTEXTGETSTYLE = SCI_FOLDDISPLAYTEXTGETSTYLE,
	PYSCR_SCI_SETDEFAULTFOLDDISPLAYTEXT = SCI_SETDEFAULTFOLDDISPLAYTEXT,
	PYSCR_SCI_GETDEFAULTFOLDDISPLAYTEXT = SCI_GETDEFAULTFOLDDISPLAYTEXT,
	PYSCR_SCI_FOLDLINE = SCI_FOLDLINE,
	PYSCR_SCI_FOLDCHILDREN = SCI_FOLDCHILDREN,
	PYSCR_SCI_EXPANDCHILDREN = SCI_EXPANDCHILDREN,
	PYSCR_SCI_FOLDALL = SCI_FOLDALL,
	PYSCR_SCI_ENSUREVISIBLE = SCI_ENSUREVISIBLE,
	PYSCR_SCI_SETAUTOMATICFOLD = SCI_SETAUTOMATICFOLD,
	PYSCR_SCI_GETAUTOMATICFOLD = SCI_GETAUTOMATICFOLD,
	PYSCR_SCI_SETFOLDFLAGS = SCI_SETFOLDFLAGS,
	PYSCR_SCI_ENSUREVISIBLEENFORCEPOLICY = SCI_ENSUREVISIBLEENFORCEPOLICY,
	PYSCR_SCI_SETTABINDENTS = SCI_SETTABINDENTS,
	PYSCR_SCI_GETTABINDENTS = SCI_GETTABINDENTS,
	PYSCR_SCI_SETBACKSPACEUNINDENTS = SCI_SETBACKSPACEUNINDENTS,
	PYSCR_SCI_GETBACKSPACEUNINDENTS = SCI_GETBACKSPACEUNINDENTS,
	PYSCR_SCI_SETMOUSEDWELLTIME = SCI_SETMOUSEDWELLTIME,
	PYSCR_SCI_GETMOUSEDWELLTIME = SCI_GETMOUSEDWELLTIME,
	PYSCR_SCI_WORDSTARTPOSITION = SCI_WORDSTARTPOSITION,
	PYSCR_SCI_WORDENDPOSITION = SCI_WORDENDPOSITION,
	PYSCR_SCI_ISRANGEWORD = SCI_ISRANGEWORD,
	PYSCR_SCI_SETIDLESTYLING = SCI_SETIDLESTYLING,
	PYSCR_SCI_GETIDLESTYLING = SCI_GETIDLESTYLING,
	PYSCR_SCI_SETWRAPMODE = SCI_SETWRAPMODE,
	PYSCR_SCI_GETWRAPMODE = SCI_GETWRAPMODE,
	PYSCR_SCI_SETWRAPVISUALFLAGS = SCI_SETWRAPVISUALFLAGS,
	PYSCR_SCI_GETWRAPVISUALFLAGS = SCI_GETWRAPVISUALFLAGS,
	PYSCR_SCI_SETWRAPVISUALFLAGSLOCATION = SCI_SETWRAPVISUALFLAGSLOCATION,
	PYSCR_SCI_GETWRAPVISUALFLAGSLOCATION = SCI_GETWRAPVISUALFLAGSLOCATION,
	PYSCR_SCI_SETWRAPSTARTINDENT = SCI_SETWRAPSTARTINDENT,
	PYSCR_SCI_GETWRAPSTARTINDENT = SCI_GETWRAPSTARTINDENT,
	PYSCR_SCI_SETWRAPINDENTMODE = SCI_SETWRAPINDENTMODE,
	PYSCR_SCI_GETWRAPINDENTMODE = SCI_GETWRAPINDENTMODE,
	PYSCR_SCI_SETLAYOUTCACHE = SCI_SETLAYOUTCACHE,
	PYSCR_SCI_GETLAYOUTCACHE = SCI_GETLAYOUTCACHE,
	PYSCR_SCI_SETSCROLLWIDTH = SCI_SETSCROLLWIDTH,
	PYSCR_SCI_GETSCROLLWIDTH = SCI_GETSCROLLWIDTH,
	PYSCR_SCI_SETSCROLLWIDTHTRACKING = SCI_SETSCROLLWIDTHTRACKING,
	PYSCR_SCI_GETSCROLLWIDTHTRACKING = SCI_GETSCROLLWIDTHTRACKING,
	PYSCR_SCI_TEXTWIDTH = SCI_TEXTWIDTH,
	PYSCR_SCI_SETENDATLASTLINE = SCI_SETENDATLASTLINE,
	PYSCR_SCI_GETENDATLASTLINE = SCI_GETENDATLASTLINE,
	PYSCR_SCI_TEXTHEIGHT = SCI_TEXTHEIGHT,
	PYSCR_SCI_SETVSCROLLBAR = SCI_SETVSCROLLBAR,
	PYSCR_SCI_GETVSCROLLBAR = SCI_GETVSCROLLBAR,
	PYSCR_SCI_APPENDTEXT = SCI_APPENDTEXT,
	PYSCR_SCI_GETPHASESDRAW = SCI_GETPHASESDRAW,
	PYSCR_SCI_SETPHASESDRAW = SCI_SETPHASESDRAW,
	PYSCR_SCI_SETFONTQUALITY = SCI_SETFONTQUALITY,
	PYSCR_SCI_GETFONTQUALITY = SCI_GETFONTQUALITY,
	PYSCR_SCI_SETFIRSTVISIBLELINE = SCI_SETFIRSTVISIBLELINE,
	PYSCR_SCI_SETMULTIPASTE = SCI_SETMULTIPASTE,
	PYSCR_SCI_GETMULTIPASTE = SCI_GETMULTIPASTE,
	PYSCR_SCI_GETTAG = SCI_GETTAG,
	PYSCR_SCI_LINESJOIN = SCI_LINESJOIN,
	PYSCR_SCI_LINESSPLIT = SCI_LINESSPLIT,
	PYSCR_SCI_SETFOLDMARGINCOLOUR = SCI_SETFOLDMARGINCOLOUR,
	PYSCR_SCI_SETFOLDMARGINHICOLOUR = SCI_SETFOLDMARGINHICOLOUR,
	PYSCR_SCI_SETACCESSIBILITY = SCI_SETACCESSIBILITY,
	PYSCR_SCI_GETACCESSIBILITY = SCI_GETACCESSIBILITY,
	PYSCR_SCI_LINEDOWN = SCI_LINEDOWN,
	PYSCR_SCI_LINEDOWNEXTEND = SCI_LINEDOWNEXTEND,
	PYSCR_SCI_LINEUP = SCI_LINEUP,
	PYSCR_SCI_LINEUPEXTEND = SCI_LINEUPEXTEND,
	PYSCR_SCI_CHARLEFT = SCI_CHARLEFT,
	PYSCR_SCI_CHARLEFTEXTEND = SCI_CHARLEFTEXTEND,
	PYSCR_SCI_CHARRIGHT = SCI_CHARRIGHT,
	PYSCR_SCI_CHARRIGHTEXTEND = SCI_CHARRIGHTEXTEND,
	PYSCR_SCI_WORDLEFT = SCI_WORDLEFT,
	PYSCR_SCI_WORDLEFTEXTEND = SCI_WORDLEFTEXTEND,
	PYSCR_SCI_WORDRIGHT = SCI_WORDRIGHT,
	PYSCR_SCI_WORDRIGHTEXTEND = SCI_WORDRIGHTEXTEND,
	PYSCR_SCI_HOME = SCI_HOME,
	PYSCR_SCI_HOMEEXTEND = SCI_HOMEEXTEND,
	PYSCR_SCI_LINEEND = SCI_LINEEND,
	PYSCR_SCI_LINEENDEXTEND = SCI_LINEENDEXTEND,
	PYSCR_SCI_DOCUMENTSTART = SCI_DOCUMENTSTART,
	PYSCR_SCI_DOCUMENTSTARTEXTEND = SCI_DOCUMENTSTARTEXTEND,
	PYSCR_SCI_DOCUMENTEND = SCI_DOCUMENTEND,
	PYSCR_SCI_DOCUMENTENDEXTEND = SCI_DOCUMENTENDEXTEND,
	PYSCR_SCI_PAGEUP = SCI_PAGEUP,
	PYSCR_SCI_PAGEUPEXTEND = SCI_PAGEUPEXTEND,
	PYSCR_SCI_PAGEDOWN = SCI_PAGEDOWN,
	PYSCR_SCI_PAGEDOWNEXTEND = SCI_PAGEDOWNEXTEND,
	PYSCR_SCI_EDITTOGGLEOVERTYPE = SCI_EDITTOGGLEOVERTYPE,
	PYSCR_SCI_CANCEL = SCI_CANCEL,
	PYSCR_SCI_DELETEBACK = SCI_DELETEBACK,
	PYSCR_SCI_TAB = SCI_TAB,
	PYSCR_SCI_BACKTAB = SCI_BACKTAB,
	PYSCR_SCI_NEWLINE = SCI_NEWLINE,
	PYSCR_SCI_FORMFEED = SCI_FORMFEED,
	PYSCR_SCI_VCHOME = SCI_VCHOME,
	PYSCR_SCI_VCHOMEEXTEND = SCI_VCHOMEEXTEND,
	PYSCR_SCI_ZOOMIN = SCI_ZOOMIN,
	PYSCR_SCI_ZOOMOUT = SCI_ZOOMOUT,
	PYSCR_SCI_DELWORDLEFT = SCI_DELWORDLEFT,
	PYSCR_SCI_DELWORDRIGHT = SCI_DELWORDRIGHT,
	PYSCR_SCI_DELWORDRIGHTEND = SCI_DELWORDRIGHTEND,
	PYSCR_SCI_LINECUT = SCI_LINECUT,
	PYSCR_SCI_LINEDELETE = SCI_LINEDELETE,
	PYSCR_SCI_LINETRANSPOSE = SCI_LINETRANSPOSE,
	PYSCR_SCI_LINEREVERSE = SCI_LINEREVERSE,
	PYSCR_SCI_LINEDUPLICATE = SCI_LINEDUPLICATE,
	PYSCR_SCI_LOWERCASE = SCI_LOWERCASE,
	PYSCR_SCI_UPPERCASE = SCI_UPPERCASE,
	PYSCR_SCI_LINESCROLLDOWN = SCI_LINESCROLLDOWN,
	PYSCR_SCI_LINESCROLLUP = SCI_LINESCROLLUP,
	PYSCR_SCI_DELETEBACKNOTLINE = SCI_DELETEBACKNOTLINE,
	PYSCR_SCI_HOMEDISPLAY = SCI_HOMEDISPLAY,
	PYSCR_SCI_HOMEDISPLAYEXTEND = SCI_HOMEDISPLAYEXTEND,
	PYSCR_SCI_LINEENDDISPLAY = SCI_LINEENDDISPLAY,
	PYSCR_SCI_LINEENDDISPLAYEXTEND = SCI_LINEENDDISPLAYEXTEND,
	PYSCR_SCI_HOMEWRAP = SCI_HOMEWRAP,
	PYSCR_SCI_HOMEWRAPEXTEND = SCI_HOMEWRAPEXTEND,
	PYSCR_SCI_LINEENDWRAP = SCI_LINEENDWRAP,
	PYSCR_SCI_LINEENDWRAPEXTEND = SCI_LINEENDWRAPEXTEND,
	PYSCR_SCI_VCHOMEWRAP = SCI_VCHOMEWRAP,
	PYSCR_SCI_VCHOMEWRAPEXTEND = SCI_VCHOMEWRAPEXTEND,
	PYSCR_SCI_LINECOPY = SCI_LINECOPY,
	PYSCR_SCI_MOVECARETINSIDEVIEW = SCI_MOVECARETINSIDEVIEW,
	PYSCR_SCI_LINELENGTH = SCI_LINELENGTH,
	PYSCR_SCI_BRACEHIGHLIGHT = SCI_BRACEHIGHLIGHT,
	PYSCR_SCI_BRACEHIGHLIGHTINDICATOR = SCI_BRACEHIGHLIGHTINDICATOR,
	PYSCR_SCI_BRACEBADLIGHT = SCI_BRACEBADLIGHT,
	PYSCR_SCI_BRACEBADLIGHTINDICATOR = SCI_BRACEBADLIGHTINDICATOR,
	PYSCR_SCI_BRACEMATCH = SCI_BRACEMATCH,
	PYSCR_SCI_BRACEMATCHNEXT = SCI_BRACEMATCHNEXT,
	PYSCR_SCI_GETVIEWEOL = SCI_GETVIEWEOL,
	PYSCR_SCI_SETVIEWEOL = SCI_SETVIEWEOL,
	PYSCR_SCI_GETDOCPOINTER = SCI_GETDOCPOINTER,
	PYSCR_SCI_SETDOCPOINTER = SCI_SETDOCPOINTER,
	PYSCR_SCI_SETMODEVENTMASK = SCI_SETMODEVENTMASK,
	PYSCR_SCI_GETEDGECOLUMN = SCI_GETEDGECOLUMN,
	PYSCR_SCI_SETEDGECOLUMN = SCI_SETEDGECOLUMN,
	PYSCR_SCI_GETEDGEMODE = SCI_GETEDGEMODE,
	PYSCR_SCI_SETEDGEMODE = SCI_SETEDGEMODE,
	PYSCR_SCI_GETEDGECOLOUR = SCI_GETEDGECOLOUR,
	PYSCR_SCI_SETEDGECOLOUR = SCI_SETEDGECOLOUR,
	PYSCR_SCI_MULTIEDGEADDLINE = SCI_MULTIEDGEADDLINE,
	PYSCR_SCI_MULTIEDGECLEARALL = SCI_MULTIEDGECLEARALL,
	PYSCR_SCI_GETMULTIEDGECOLUMN = SCI_GETMULTIEDGECOLUMN,
	PYSCR_SCI_SEARCHANCHOR = SCI_SEARCHANCHOR,
	PYSCR_SCI_SEARCHNEXT = SCI_SEARCHNEXT,
	PYSCR_SCI_SEARCHPREV = SCI_SEARCHPREV,
	PYSCR_SCI_LINESONSCREEN = SCI_LINESONSCREEN,
	PYSCR_SCI_USEPOPUP = SCI_USEPOPUP,
	PYSCR_SCI_SELECTIONISRECTANGLE = SCI_SELECTIONISRECTANGLE,
	PYSCR_SCI_SETZOOM = SCI_SETZOOM,
	PYSCR_SCI_GETZOOM = SCI_GETZOOM,
	PYSCR_SCI_CREATEDOCUMENT = SCI_CREATEDOCUMENT,
	PYSCR_SCI_ADDREFDOCUMENT = SCI_ADDREFDOCUMENT,
	PYSCR_SCI_RELEASEDOCUMENT = SCI_RELEASEDOCUMENT,
	PYSCR_SCI_GETDOCUMENTOPTIONS = SCI_GETDOCUMENTOPTIONS,
	PYSCR_SCI_GETMODEVENTMASK = SCI_GETMODEVENTMASK,
	PYSCR_SCI_SETCOMMANDEVENTS = SCI_SETCOMMANDEVENTS,
	PYSCR_SCI_GETCOMMANDEVENTS = SCI_GETCOMMANDEVENTS,
	PYSCR_SCI_SETFOCUS = SCI_SETFOCUS,
	PYSCR_SCI_GETFOCUS = SCI_GETFOCUS,
	PYSCR_SCI_SETSTATUS = SCI_SETSTATUS,
	PYSCR_SCI_GETSTATUS = SCI_GETSTATUS,
	PYSCR_SCI_SETMOUSEDOWNCAPTURES = SCI_SETMOUSEDOWNCAPTURES,
	PYSCR_SCI_GETMOUSEDOWNCAPTURES = SCI_GETMOUSEDOWNCAPTURES,
	PYSCR_SCI_SETMOUSEWHEELCAPTURES = SCI_SETMOUSEWHEELCAPTURES,
	PYSCR_SCI_GETMOUSEWHEELCAPTURES = SCI_GETMOUSEWHEELCAPTURES,
	PYSCR_SCI_SETCURSOR = SCI_SETCURSOR,
	PYSCR_SCI_GETCURSOR = SCI_GETCURSOR,
	PYSCR_SCI_SETCONTROLCHARSYMBOL = SCI_SETCONTROLCHARSYMBOL,
	PYSCR_SCI_GETCONTROLCHARSYMBOL = SCI_GETCONTROLCHARSYMBOL,
	PYSCR_SCI_WORDPARTLEFT = SCI_WORDPARTLEFT,
	PYSCR_SCI_WORDPARTLEFTEXTEND = SCI_WORDPARTLEFTEXTEND,
	PYSCR_SCI_WORDPARTRIGHT = SCI_WORDPARTRIGHT,
	PYSCR_SCI_WORDPARTRIGHTEXTEND = SCI_WORDPARTRIGHTEXTEND,
	PYSCR_SCI_SETVISIBLEPOLICY = SCI_SETVISIBLEPOLICY,
	PYSCR_SCI_DELLINELEFT = SCI_DELLINELEFT,
	PYSCR_SCI_DELLINERIGHT = SCI_DELLINERIGHT,
	PYSCR_SCI_SETXOFFSET = SCI_SETXOFFSET,
	PYSCR_SCI_GETXOFFSET = SCI_GETXOFFSET,
	PYSCR_SCI_CHOOSECARETX = SCI_CHOOSECARETX,
	PYSCR_SCI_GRABFOCUS = SCI_GRABFOCUS,
	PYSCR_SCI_SETXCARETPOLICY = SCI_SETXCARETPOLICY,
	PYSCR_SCI_SETYCARETPOLICY = SCI_SETYCARETPOLICY,
	PYSCR_SCI_SETPRINTWRAPMODE = SCI_SETPRINTWRAPMODE,
	PYSCR_SCI_GETPRINTWRAPMODE = SCI_GETPRINTWRAPMODE,
	PYSCR_SCI_SETHOTSPOTACTIVEFORE = SCI_SETHOTSPOTACTIVEFORE,
	PYSCR_SCI_GETHOTSPOTACTIVEFORE = SCI_GETHOTSPOTACTIVEFORE,
	PYSCR_SCI_SETHOTSPOTACTIVEBACK = SCI_SETHOTSPOTACTIVEBACK,
	PYSCR_SCI_GETHOTSPOTACTIVEBACK = SCI_GETHOTSPOTACTIVEBACK,
	PYSCR_SCI_SETHOTSPOTACTIVEUNDERLINE = SCI_SETHOTSPOTACTIVEUNDERLINE,
	PYSCR_SCI_GETHOTSPOTACTIVEUNDERLINE = SCI_GETHOTSPOTACTIVEUNDERLINE,
	PYSCR_SCI_SETHOTSPOTSINGLELINE = SCI_SETHOTSPOTSINGLELINE,
	PYSCR_SCI_GETHOTSPOTSINGLELINE = SCI_GETHOTSPOTSINGLELINE,
	PYSCR_SCI_PARADOWN = SCI_PARADOWN,
	PYSCR_SCI_PARADOWNEXTEND = SCI_PARADOWNEXTEND,
	PYSCR_SCI_PARAUP = SCI_PARAUP,
	PYSCR_SCI_PARAUPEXTEND = SCI_PARAUPEXTEND,
	PYSCR_SCI_POSITIONBEFORE = SCI_POSITIONBEFORE,
	PYSCR_SCI_POSITIONAFTER = SCI_POSITIONAFTER,
	PYSCR_SCI_POSITIONRELATIVE = SCI_POSITIONRELATIVE,
	PYSCR_SCI_POSITIONRELATIVECODEUNITS = SCI_POSITIONRELATIVECODEUNITS,
	PYSCR_SCI_COPYRANGE = SCI_COPYRANGE,
	PYSCR_SCI_COPYTEXT = SCI_COPYTEXT,
	PYSCR_SCI_SETSELECTIONMODE = SCI_SETSELECTIONMODE,
	PYSCR_SCI_GETSELECTIONMODE = SCI_GETSELECTIONMODE,
	PYSCR_SCI_GETMOVEEXTENDSSELECTION = SCI_GETMOVEEXTENDSSELECTION,
	PYSCR_SCI_GETLINESELSTARTPOSITION = SCI_GETLINESELSTARTPOSITION,
	PYSCR_SCI_GETLINESELENDPOSITION = SCI_GETLINESELENDPOSITION,
	PYSCR_SCI_LINEDOWNRECTEXTEND = SCI_LINEDOWNRECTEXTEND,
	PYSCR_SCI_LINEUPRECTEXTEND = SCI_LINEUPRECTEXTEND,
	PYSCR_SCI_CHARLEFTRECTEXTEND = SCI_CHARLEFTRECTEXTEND,
	PYSCR_SCI_CHARRIGHTRECTEXTEND = SCI_CHARRIGHTRECTEXTEND,
	PYSCR_SCI_HOMERECTEXTEND = SCI_HOMERECTEXTEND,
	PYSCR_SCI_VCHOMERECTEXTEND = SCI_VCHOMERECTEXTEND,
	PYSCR_SCI_LINEENDRECTEXTEND = SCI_LINEENDRECTEXTEND,
	PYSCR_SCI_PAGEUPRECTEXTEND = SCI_PAGEUPRECTEXTEND,
	PYSCR_SCI_PAGEDOWNRECTEXTEND = SCI_PAGEDOWNRECTEXTEND,
	PYSCR_SCI_STUTTEREDPAGEUP = SCI_STUTTEREDPAGEUP,
	PYSCR_SCI_STUTTEREDPAGEUPEXTEND = SCI_STUTTEREDPAGEUPEXTEND,
	PYSCR_SCI_STUTTEREDPAGEDOWN = SCI_STUTTEREDPAGEDOWN,
	PYSCR_SCI_STUTTEREDPAGEDOWNEXTEND = SCI_STUTTEREDPAGEDOWNEXTEND,
	PYSCR_SCI_WORDLEFTEND = SCI_WORDLEFTEND,
	PYSCR_SCI_WORDLEFTENDEXTEND = SCI_WORDLEFTENDEXTEND,
	PYSCR_SCI_WORDRIGHTEND = SCI_WORDRIGHTEND,
	PYSCR_SCI_WORDRIGHTENDEXTEND = SCI_WORDRIGHTENDEXTEND,
	PYSCR_SCI_SETWHITESPACECHARS = SCI_SETWHITESPACECHARS,
	PYSCR_SCI_GETWHITESPACECHARS = SCI_GETWHITESPACECHARS,
	PYSCR_SCI_SETPUNCTUATIONCHARS = SCI_SETPUNCTUATIONCHARS,
	PYSCR_SCI_GETPUNCTUATIONCHARS = SCI_GETPUNCTUATIONCHARS,
	PYSCR_SCI_SETCHARSDEFAULT = SCI_SETCHARSDEFAULT,
	PYSCR_SCI_AUTOCGETCURRENT = SCI_AUTOCGETCURRENT,
	PYSCR_SCI_AUTOCGETCURRENTTEXT = SCI_AUTOCGETCURRENTTEXT,
	PYSCR_SCI_AUTOCSETCASEINSENSITIVEBEHAVIOUR = SCI_AUTOCSETCASEINSENSITIVEBEHAVIOUR,
	PYSCR_SCI_AUTOCGETCASEINSENSITIVEBEHAVIOUR = SCI_AUTOCGETCASEINSENSITIVEBEHAVIOUR,
	PYSCR_SCI_AUTOCSETMULTI = SCI_AUTOCSETMULTI,
	PYSCR_SCI_AUTOCGETMULTI = SCI_AUTOCGETMULTI,
	PYSCR_SCI_AUTOCSETORDER = SCI_AUTOCSETORDER,
	PYSCR_SCI_AUTOCGETORDER = SCI_AUTOCGETORDER,
	PYSCR_SCI_ALLOCATE = SCI_ALLOCATE,
	PYSCR_SCI_TARGETASUTF8 = SCI_TARGETASUTF8,
	PYSCR_SCI_SETLENGTHFORENCODE = SCI_SETLENGTHFORENCODE,
	PYSCR_SCI_ENCODEDFROMUTF8 = SCI_ENCODEDFROMUTF8,
	PYSCR_SCI_FINDCOLUMN = SCI_FINDCOLUMN,
	PYSCR_SCI_GETCARETSTICKY = SCI_GETCARETSTICKY,
	PYSCR_SCI_SETCARETSTICKY = SCI_SETCARETSTICKY,
	PYSCR_SCI_TOGGLECARETSTICKY = SCI_TOGGLECARETSTICKY,
	PYSCR_SCI_SETPASTECONVERTENDINGS = SCI_SETPASTECONVERTENDINGS,
	PYSCR_SCI_GETPASTECONVERTENDINGS = SCI_GETPASTECONVERTENDINGS,
	PYSCR_SCI_REPLACERECTANGULAR = SCI_REPLACERECTANGULAR,
	PYSCR_SCI_SELECTIONDUPLICATE = SCI_SELECTIONDUPLICATE,
	PYSCR_SCI_SETCARETLINEBACKALPHA = SCI_SETCARETLINEBACKALPHA,
	PYSCR_SCI_GETCARETLINEBACKALPHA = SCI_GETCARETLINEBACKALPHA,
	PYSCR_SCI_SETCARETSTYLE = SCI_SETCARETSTYLE,
	PYSCR_SCI_GETCARETSTYLE = SCI_GETCARETSTYLE,
	PYSCR_SCI_SETINDICATORCURRENT = SCI_SETINDICATORCURRENT,
	PYSCR_SCI_GETINDICATORCURRENT = SCI_GETINDICATORCURRENT,
	PYSCR_SCI_SETINDICATORVALUE = SCI_SETINDICATORVALUE,
	PYSCR_SCI_GETINDICATORVALUE = SCI_GETINDICATORVALUE,
	PYSCR_SCI_INDICATORFILLRANGE = SCI_INDICATORFILLRANGE,
	PYSCR_SCI_INDICATORCLEARRANGE = SCI_INDICATORCLEARRANGE,
	PYSCR_SCI_INDICATORALLONFOR = SCI_INDICATORALLONFOR,
	PYSCR_SCI_INDICATORVALUEAT = SCI_INDICATORVALUEAT,
	PYSCR_SCI_INDICATORSTART = SCI_INDICATORSTART,
	PYSCR_SCI_INDICATOREND = SCI_INDICATOREND,
	PYSCR_SCI_SETPOSITIONCACHE = SCI_SETPOSITIONCACHE,
	PYSCR_SCI_GETPOSITIONCACHE = SCI_GETPOSITIONCACHE,
	PYSCR_SCI_SETLAYOUTTHREADS = SCI_SETLAYOUTTHREADS,
	PYSCR_SCI_GETLAYOUTTHREADS = SCI_GETLAYOUTTHREADS,
	PYSCR_SCI_COPYALLOWLINE = SCI_COPYALLOWLINE,
	PYSCR_SCI_GETCHARACTERPOINTER = SCI_GETCHARACTERPOINTER,
	PYSCR_SCI_GETRANGEPOINTER = SCI_GETRANGEPOINTER,
	PYSCR_SCI_GETGAPPOSITION = SCI_GETGAPPOSITION,
	PYSCR_SCI_INDICSETALPHA = SCI_INDICSETALPHA,
	PYSCR_SCI_INDICGETALPHA = SCI_INDICGETALPHA,
	PYSCR_SCI_INDICSETOUTLINEALPHA = SCI_INDICSETOUTLINEALPHA,
	PYSCR_SCI_INDICGETOUTLINEALPHA = SCI_INDICGETOUTLINEALPHA,
	PYSCR_SCI_SETEXTRAASCENT = SCI_SETEXTRAASCENT,
	PYSCR_SCI_GETEXTRAASCENT = SCI_GETEXTRAASCENT,
	PYSCR_SCI_SETEXTRADESCENT = SCI_SETEXTRADESCENT,
	PYSCR_SCI_GETEXTRADESCENT = SCI_GETEXTRADESCENT,
	PYSCR_SCI_MARKERSYMBOLDEFINED = SCI_MARKERSYMBOLDEFINED,
	PYSCR_SCI_MARGINSETTEXT = SCI_MARGINSETTEXT,
	PYSCR_SCI_MARGINGETTEXT = SCI_MARGINGETTEXT,
	PYSCR_SCI_MARGINSETSTYLE = SCI_MARGINSETSTYLE,
	PYSCR_SCI_MARGINGETSTYLE = SCI_MARGINGETSTYLE,
	PYSCR_SCI_MARGINSETSTYLES = SCI_MARGINSETSTYLES,
	PYSCR_SCI_MARGINGETSTYLES = SCI_MARGINGETSTYLES,
	PYSCR_SCI_MARGINTEXTCLEARALL = SCI_MARGINTEXTCLEARALL,
	PYSCR_SCI_MARGINSETSTYLEOFFSET = SCI_MARGINSETSTYLEOFFSET,
	PYSCR_SCI_MARGINGETSTYLEOFFSET = SCI_MARGINGETSTYLEOFFSET,
	PYSCR_SCI_SETMARGINOPTIONS = SCI_SETMARGINOPTIONS,
	PYSCR_SCI_GETMARGINOPTIONS = SCI_GETMARGINOPTIONS,
	PYSCR_SCI_ANNOTATIONSETTEXT = SCI_ANNOTATIONSETTEXT,
	PYSCR_SCI_ANNOTATIONGETTEXT = SCI_ANNOTATIONGETTEXT,
	PYSCR_SCI_ANNOTATIONSETSTYLE = SCI_ANNOTATIONSETSTYLE,
	PYSCR_SCI_ANNOTATIONGETSTYLE = SCI_ANNOTATIONGETSTYLE,
	PYSCR_SCI_ANNOTATIONSETSTYLES = SCI_ANNOTATIONSETSTYLES,
	PYSCR_SCI_ANNOTATIONGETSTYLES = SCI_ANNOTATIONGETSTYLES,
	PYSCR_SCI_ANNOTATIONGETLINES = SCI_ANNOTATIONGETLINES,
	PYSCR_SCI_ANNOTATIONCLEARALL = SCI_ANNOTATIONCLEARALL,
	PYSCR_SCI_ANNOTATIONSETVISIBLE = SCI_ANNOTATIONSETVISIBLE,
	PYSCR_SCI_ANNOTATIONGETVISIBLE = SCI_ANNOTATIONGETVISIBLE,
	PYSCR_SCI_ANNOTATIONSETSTYLEOFFSET = SCI_ANNOTATIONSETSTYLEOFFSET,
	PYSCR_SCI_ANNOTATIONGETSTYLEOFFSET = SCI_ANNOTATIONGETSTYLEOFFSET,
	PYSCR_SCI_RELEASEALLEXTENDEDSTYLES = SCI_RELEASEALLEXTENDEDSTYLES,
	PYSCR_SCI_ALLOCATEEXTENDEDSTYLES = SCI_ALLOCATEEXTENDEDSTYLES,
	PYSCR_SCI_ADDUNDOACTION = SCI_ADDUNDOACTION,
	PYSCR_SCI_CHARPOSITIONFROMPOINT = SCI_CHARPOSITIONFROMPOINT,
	PYSCR_SCI_CHARPOSITIONFROMPOINTCLOSE = SCI_CHARPOSITIONFROMPOINTCLOSE,
	PYSCR_SCI_SETMOUSESELECTIONRECTANGULARSWITCH = SCI_SETMOUSESELECTIONRECTANGULARSWITCH,
	PYSCR_SCI_GETMOUSESELECTIONRECTANGULARSWITCH = SCI_GETMOUSESELECTIONRECTANGULARSWITCH,
	PYSCR_SCI_SETMULTIPLESELECTION = SCI_SETMULTIPLESELECTION,
	PYSCR_SCI_GETMULTIPLESELECTION = SCI_GETMULTIPLESELECTION,
	PYSCR_SCI_SETADDITIONALSELECTIONTYPING = SCI_SETADDITIONALSELECTIONTYPING,
	PYSCR_SCI_GETADDITIONALSELECTIONTYPING = SCI_GETADDITIONALSELECTIONTYPING,
	PYSCR_SCI_SETADDITIONALCARETSBLINK = SCI_SETADDITIONALCARETSBLINK,
	PYSCR_SCI_GETADDITIONALCARETSBLINK = SCI_GETADDITIONALCARETSBLINK,
	PYSCR_SCI_SETADDITIONALCARETSVISIBLE = SCI_SETADDITIONALCARETSVISIBLE,
	PYSCR_SCI_GETADDITIONALCARETSVISIBLE = SCI_GETADDITIONALCARETSVISIBLE,
	PYSCR_SCI_GETSELECTIONS = SCI_GETSELECTIONS,
	PYSCR_SCI_GETSELECTIONEMPTY = SCI_GETSELECTIONEMPTY,
	PYSCR_SCI_CLEARSELECTIONS = SCI_CLEARSELECTIONS,
	PYSCR_SCI_SETSELECTION = SCI_SETSELECTION,
	PYSCR_SCI_ADDSELECTION = SCI_ADDSELECTION,
	PYSCR_SCI_DROPSELECTIONN = SCI_DROPSELECTIONN,
	PYSCR_SCI_SETMAINSELECTION = SCI_SETMAINSELECTION,
	PYSCR_SCI_GETMAINSELECTION = SCI_GETMAINSELECTION,
	PYSCR_SCI_SETSELECTIONNCARET = SCI_SETSELECTIONNCARET,
	PYSCR_SCI_GETSELECTIONNCARET = SCI_GETSELECTIONNCARET,
	PYSCR_SCI_SETSELECTIONNANCHOR = SCI_SETSELECTIONNANCHOR,
	PYSCR_SCI_GETSELECTIONNANCHOR = SCI_GETSELECTIONNANCHOR,
	PYSCR_SCI_SETSELECTIONNCARETVIRTUALSPACE = SCI_SETSELECTIONNCARETVIRTUALSPACE,
	PYSCR_SCI_GETSELECTIONNCARETVIRTUALSPACE = SCI_GETSELECTIONNCARETVIRTUALSPACE,
	PYSCR_SCI_SETSELECTIONNANCHORVIRTUALSPACE = SCI_SETSELECTIONNANCHORVIRTUALSPACE,
	PYSCR_SCI_GETSELECTIONNANCHORVIRTUALSPACE = SCI_GETSELECTIONNANCHORVIRTUALSPACE,
	PYSCR_SCI_SETSELECTIONNSTART = SCI_SETSELECTIONNSTART,
	PYSCR_SCI_GETSELECTIONNSTART = SCI_GETSELECTIONNSTART,
	PYSCR_SCI_GETSELECTIONNSTARTVIRTUALSPACE = SCI_GETSELECTIONNSTARTVIRTUALSPACE,
	PYSCR_SCI_SETSELECTIONNEND = SCI_SETSELECTIONNEND,
	PYSCR_SCI_GETSELECTIONNENDVIRTUALSPACE = SCI_GETSELECTIONNENDVIRTUALSPACE,
	PYSCR_SCI_GETSELECTIONNEND = SCI_GETSELECTIONNEND,
	PYSCR_SCI_SETRECTANGULARSELECTIONCARET = SCI_SETRECTANGULARSELECTIONCARET,
	PYSCR_SCI_GETRECTANGULARSELECTIONCARET = SCI_GETRECTANGULARSELECTIONCARET,
	PYSCR_SCI_SETRECTANGULARSELECTIONANCHOR = SCI_SETRECTANGULARSELECTIONANCHOR,
	PYSCR_SCI_GETRECTANGULARSELECTIONANCHOR = SCI_GETRECTANGULARSELECTIONANCHOR,
	PYSCR_SCI_SETRECTANGULARSELECTIONCARETVIRTUALSPACE = SCI_SETRECTANGULARSELECTIONCARETVIRTUALSPACE,
	PYSCR_SCI_GETRECTANGULARSELECTIONCARETVIRTUALSPACE = SCI_GETRECTANGULARSELECTIONCARETVIRTUALSPACE,
	PYSCR_SCI_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE = SCI_SETRECTANGULARSELECTIONANCHORVIRTUALSPACE,
	PYSCR_SCI_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE = SCI_GETRECTANGULARSELECTIONANCHORVIRTUALSPACE,
	PYSCR_SCI_SETVIRTUALSPACEOPTIONS = SCI_SETVIRTUALSPACEOPTIONS,
	PYSCR_SCI_GETVIRTUALSPACEOPTIONS = SCI_GETVIRTUALSPACEOPTIONS,
	PYSCR_SCI_SETRECTANGULARSELECTIONMODIFIER = SCI_SETRECTANGULARSELECTIONMODIFIER,
	PYSCR_SCI_GETRECTANGULARSELECTIONMODIFIER = SCI_GETRECTANGULARSELECTIONMODIFIER,
	PYSCR_SCI_SETADDITIONALSELFORE = SCI_SETADDITIONALSELFORE,
	PYSCR_SCI_SETADDITIONALSELBACK = SCI_SETADDITIONALSELBACK,
	PYSCR_SCI_SETADDITIONALSELALPHA = SCI_SETADDITIONALSELALPHA,
	PYSCR_SCI_GETADDITIONALSELALPHA = SCI_GETADDITIONALSELALPHA,
	PYSCR_SCI_SETADDITIONALCARETFORE = SCI_SETADDITIONALCARETFORE,
	PYSCR_SCI_GETADDITIONALCARETFORE = SCI_GETADDITIONALCARETFORE,
	PYSCR_SCI_ROTATESELECTION = SCI_ROTATESELECTION,
	PYSCR_SCI_SWAPMAINANCHORCARET = SCI_SWAPMAINANCHORCARET,
	PYSCR_SCI_MULTIPLESELECTADDNEXT = SCI_MULTIPLESELECTADDNEXT,
	PYSCR_SCI_MULTIPLESELECTADDEACH = SCI_MULTIPLESELECTADDEACH,
	PYSCR_SCI_CHANGELEXERSTATE = SCI_CHANGELEXERSTATE,
	PYSCR_SCI_CONTRACTEDFOLDNEXT = SCI_CONTRACTEDFOLDNEXT,
	PYSCR_SCI_VERTICALCENTRECARET = SCI_VERTICALCENTRECARET,
	PYSCR_SCI_MOVESELECTEDLINESUP = SCI_MOVESELECTEDLINESUP,
	PYSCR_SCI_MOVESELECTEDLINESDOWN = SCI_MOVESELECTEDLINESDOWN,
	PYSCR_SCI_SETIDENTIFIER = SCI_SETIDENTIFIER,
	PYSCR_SCI_GETIDENTIFIER = SCI_GETIDENTIFIER,
	PYSCR_SCI_RGBAIMAGESETWIDTH = SCI_RGBAIMAGESETWIDTH,
	PYSCR_SCI_RGBAIMAGESETHEIGHT = SCI_RGBAIMAGESETHEIGHT,
	PYSCR_SCI_RGBAIMAGESETSCALE = SCI_RGBAIMAGESETSCALE,
	PYSCR_SCI_MARKERDEFINERGBAIMAGE = SCI_MARKERDEFINERGBAIMAGE,
	PYSCR_SCI_REGISTERRGBAIMAGE = SCI_REGISTERRGBAIMAGE,
	PYSCR_SCI_SCROLLTOSTART = SCI_SCROLLTOSTART,
	PYSCR_SCI_SCROLLTOEND = SCI_SCROLLTOEND,
	PYSCR_SCI_SETTECHNOLOGY = SCI_SETTECHNOLOGY,
	PYSCR_SCI_GETTECHNOLOGY = SCI_GETTECHNOLOGY,
	PYSCR_SCI_CREATELOADER = SCI_CREATELOADER,
	PYSCR_SCI_FINDINDICATORSHOW = SCI_FINDINDICATORSHOW,
	PYSCR_SCI_FINDINDICATORFLASH = SCI_FINDINDICATORFLASH,
	PYSCR_SCI_FINDINDICATORHIDE = SCI_FINDINDICATORHIDE,
	PYSCR_SCI_VCHOMEDISPLAY = SCI_VCHOMEDISPLAY,
	PYSCR_SCI_VCHOMEDISPLAYEXTEND = SCI_VCHOMEDISPLAYEXTEND,
	PYSCR_SCI_GETCARETLINEVISIBLEALWAYS = SCI_GETCARETLINEVISIBLEALWAYS,
	PYSCR_SCI_SETCARETLINEVISIBLEALWAYS = SCI_SETCARETLINEVISIBLEALWAYS,
	PYSCR_SCI_SETLINEENDTYPESALLOWED = SCI_SETLINEENDTYPESALLOWED,
	PYSCR_SCI_GETLINEENDTYPESALLOWED = SCI_GETLINEENDTYPESALLOWED,
	PYSCR_SCI_GETLINEENDTYPESACTIVE = SCI_GETLINEENDTYPESACTIVE,
	PYSCR_SCI_SETREPRESENTATION = SCI_SETREPRESENTATION,
	PYSCR_SCI_GETREPRESENTATION = SCI_GETREPRESENTATION,
	PYSCR_SCI_CLEARREPRESENTATION = SCI_CLEARREPRESENTATION,
	PYSCR_SCI_CLEARALLREPRESENTATIONS = SCI_CLEARALLREPRESENTATIONS,
	PYSCR_SCI_SETREPRESENTATIONAPPEARANCE = SCI_SETREPRESENTATIONAPPEARANCE,
	PYSCR_SCI_GETREPRESENTATIONAPPEARANCE = SCI_GETREPRESENTATIONAPPEARANCE,
	PYSCR_SCI_SETREPRESENTATIONCOLOUR = SCI_SETREPRESENTATIONCOLOUR,
	PYSCR_SCI_GETREPRESENTATIONCOLOUR = SCI_GETREPRESENTATIONCOLOUR,
	PYSCR_SCI_EOLANNOTATIONSETTEXT = SCI_EOLANNOTATIONSETTEXT,
	PYSCR_SCI_EOLANNOTATIONGETTEXT = SCI_EOLANNOTATIONGETTEXT,
	PYSCR_SCI_EOLANNOTATIONSETSTYLE = SCI_EOLANNOTATIONSETSTYLE,
	PYSCR_SCI_EOLANNOTATIONGETSTYLE = SCI_EOLANNOTATIONGETSTYLE,
	PYSCR_SCI_EOLANNOTATIONCLEARALL = SCI_EOLANNOTATIONCLEARALL,
	PYSCR_SCI_EOLANNOTATIONSETVISIBLE = SCI_EOLANNOTATIONSETVISIBLE,
	PYSCR_SCI_EOLANNOTATIONGETVISIBLE = SCI_EOLANNOTATIONGETVISIBLE,
	PYSCR_SCI_EOLANNOTATIONSETSTYLEOFFSET = SCI_EOLANNOTATIONSETSTYLEOFFSET,
	PYSCR_SCI_EOLANNOTATIONGETSTYLEOFFSET = SCI_EOLANNOTATIONGETSTYLEOFFSET,
	PYSCR_SCI_SUPPORTSFEATURE = SCI_SUPPORTSFEATURE,
	PYSCR_SCI_GETLINECHARACTERINDEX = SCI_GETLINECHARACTERINDEX,
	PYSCR_SCI_ALLOCATELINECHARACTERINDEX = SCI_ALLOCATELINECHARACTERINDEX,
	PYSCR_SCI_RELEASELINECHARACTERINDEX = SCI_RELEASELINECHARACTERINDEX,
	PYSCR_SCI_LINEFROMINDEXPOSITION = SCI_LINEFROMINDEXPOSITION,
	PYSCR_SCI_INDEXPOSITIONFROMLINE = SCI_INDEXPOSITIONFROMLINE,
	PYSCR_SCI_STARTRECORD = SCI_STARTRECORD,
	PYSCR_SCI_STOPRECORD = SCI_STOPRECORD,
	PYSCR_SCI_GETLEXER = SCI_GETLEXER,
	PYSCR_SCI_COLOURISE = SCI_COLOURISE,
	PYSCR_SCI_SETPROPERTY = SCI_SETPROPERTY,
	PYSCR_SCI_SETKEYWORDS = SCI_SETKEYWORDS,
	PYSCR_SCI_GETPROPERTY = SCI_GETPROPERTY,
	PYSCR_SCI_GETPROPERTYEXPANDED = SCI_GETPROPERTYEXPANDED,
	PYSCR_SCI_GETPROPERTYINT = SCI_GETPROPERTYINT,
	PYSCR_SCI_GETLEXERLANGUAGE = SCI_GETLEXERLANGUAGE,
	PYSCR_SCI_PRIVATELEXERCALL = SCI_PRIVATELEXERCALL,
	PYSCR_SCI_PROPERTYNAMES = SCI_PROPERTYNAMES,
	PYSCR_SCI_PROPERTYTYPE = SCI_PROPERTYTYPE,
	PYSCR_SCI_DESCRIBEPROPERTY = SCI_DESCRIBEPROPERTY,
	PYSCR_SCI_DESCRIBEKEYWORDSETS = SCI_DESCRIBEKEYWORDSETS,
	PYSCR_SCI_GETLINEENDTYPESSUPPORTED = SCI_GETLINEENDTYPESSUPPORTED,
	PYSCR_SCI_ALLOCATESUBSTYLES = SCI_ALLOCATESUBSTYLES,
	PYSCR_SCI_GETSUBSTYLESSTART = SCI_GETSUBSTYLESSTART,
	PYSCR_SCI_GETSUBSTYLESLENGTH = SCI_GETSUBSTYLESLENGTH,
	PYSCR_SCI_GETSTYLEFROMSUBSTYLE = SCI_GETSTYLEFROMSUBSTYLE,
	PYSCR_SCI_GETPRIMARYSTYLEFROMSTYLE = SCI_GETPRIMARYSTYLEFROMSTYLE,
	PYSCR_SCI_FREESUBSTYLES = SCI_FREESUBSTYLES,
	PYSCR_SCI_SETIDENTIFIERS = SCI_SETIDENTIFIERS,
	PYSCR_SCI_DISTANCETOSECONDARYSTYLES = SCI_DISTANCETOSECONDARYSTYLES,
	PYSCR_SCI_GETSUBSTYLEBASES = SCI_GETSUBSTYLEBASES,
	PYSCR_SCI_GETNAMEDSTYLES = SCI_GETNAMEDSTYLES,
	PYSCR_SCI_NAMEOFSTYLE = SCI_NAMEOFSTYLE,
	PYSCR_SCI_TAGSOFSTYLE = SCI_TAGSOFSTYLE,
	PYSCR_SCI_DESCRIPTIONOFSTYLE = SCI_DESCRIPTIONOFSTYLE,
	PYSCR_SCI_SETILEXER = SCI_SETILEXER,
	PYSCR_SCI_GETBIDIRECTIONAL = SCI_GETBIDIRECTIONAL,
	PYSCR_SCI_SETBIDIRECTIONAL = SCI_SETBIDIRECTIONAL
};
enum ScintillaNotification
{
	PYSCR_SCN_STYLENEEDED = PYSCN_STYLENEEDED,
	PYSCR_SCN_CHARADDED = PYSCN_CHARADDED,
	PYSCR_SCN_SAVEPOINTREACHED = PYSCN_SAVEPOINTREACHED,
	PYSCR_SCN_SAVEPOINTLEFT = PYSCN_SAVEPOINTLEFT,
	PYSCR_SCN_MODIFYATTEMPTRO = PYSCN_MODIFYATTEMPTRO,
	PYSCR_SCN_KEY = PYSCN_KEY,
	PYSCR_SCN_DOUBLECLICK = PYSCN_DOUBLECLICK,
	PYSCR_SCN_UPDATEUI = PYSCN_UPDATEUI,
	PYSCR_SCN_MODIFIED = PYSCN_MODIFIED,
	PYSCR_SCN_MACRORECORD = PYSCN_MACRORECORD,
	PYSCR_SCN_MARGINCLICK = PYSCN_MARGINCLICK,
	PYSCR_SCN_NEEDSHOWN = PYSCN_NEEDSHOWN,
	PYSCR_SCN_PAINTED = PYSCN_PAINTED,
	PYSCR_SCN_USERLISTSELECTION = PYSCN_USERLISTSELECTION,
	PYSCR_SCN_URIDROPPED = PYSCN_URIDROPPED,
	PYSCR_SCN_DWELLSTART = PYSCN_DWELLSTART,
	PYSCR_SCN_DWELLEND = PYSCN_DWELLEND,
	PYSCR_SCN_ZOOM = PYSCN_ZOOM,
	PYSCR_SCN_HOTSPOTCLICK = PYSCN_HOTSPOTCLICK,
	PYSCR_SCN_HOTSPOTDOUBLECLICK = PYSCN_HOTSPOTDOUBLECLICK,
	PYSCR_SCN_CALLTIPCLICK = PYSCN_CALLTIPCLICK,
	PYSCR_SCN_AUTOCSELECTION = PYSCN_AUTOCSELECTION,
	PYSCR_SCN_INDICATORCLICK = PYSCN_INDICATORCLICK,
	PYSCR_SCN_INDICATORRELEASE = PYSCN_INDICATORRELEASE,
	PYSCR_SCN_AUTOCCANCELLED = PYSCN_AUTOCCANCELLED,
	PYSCR_SCN_AUTOCCHARDELETED = PYSCN_AUTOCCHARDELETED,
	PYSCR_SCN_HOTSPOTRELEASECLICK = PYSCN_HOTSPOTRELEASECLICK,
	PYSCR_SCN_FOCUSIN = PYSCN_FOCUSIN,
	PYSCR_SCN_FOCUSOUT = PYSCN_FOCUSOUT,
	PYSCR_SCN_AUTOCCOMPLETED = PYSCN_AUTOCCOMPLETED,
	PYSCR_SCN_MARGINRIGHTCLICK = PYSCN_MARGINRIGHTCLICK,
	PYSCR_SCN_AUTOCSELECTIONCHANGE = PYSCN_AUTOCSELECTIONCHANGE
};
	/* --Autogenerated ---------------------------------------------- */
#endif
