#ifndef _SCINTILLANOTIFICATIONS_H
#define _SCINTILLANOTIFICATIONS_H

#ifndef SCINTILLA_H
#include "Scintilla.h"
#endif

enum ScintillaNotificationInternal
{
	PYSCN_STYLENEEDED			= SCN_STYLENEEDED,
	PYSCN_CHARADDED				= SCN_CHARADDED,
	PYSCN_SAVEPOINTREACHED		= SCN_SAVEPOINTREACHED,
	PYSCN_SAVEPOINTLEFT			= SCN_SAVEPOINTLEFT,
	PYSCN_MODIFYATTEMPTRO		= SCN_MODIFYATTEMPTRO,
	PYSCN_KEY					= SCN_KEY,
	PYSCN_DOUBLECLICK			= SCN_DOUBLECLICK,
	PYSCN_UPDATEUI				= SCN_UPDATEUI,
	PYSCN_MODIFIED				= SCN_MODIFIED,
	PYSCN_MACRORECORD			= SCN_MACRORECORD,
	PYSCN_MARGINCLICK			= SCN_MARGINCLICK,
	PYSCN_NEEDSHOWN				= SCN_NEEDSHOWN,
	PYSCN_PAINTED				= SCN_PAINTED,
	PYSCN_USERLISTSELECTION		= SCN_USERLISTSELECTION,
	PYSCN_URIDROPPED			= SCN_URIDROPPED,
	PYSCN_DWELLSTART			= SCN_DWELLSTART,
	PYSCN_DWELLEND				= SCN_DWELLEND,
	PYSCN_ZOOM					= SCN_ZOOM,
	PYSCN_HOTSPOTCLICK			= SCN_HOTSPOTCLICK,
	PYSCN_HOTSPOTDOUBLECLICK	= SCN_HOTSPOTDOUBLECLICK,
	PYSCN_INDICATORCLICK		= SCN_INDICATORCLICK,
	PYSCN_INDICATORRELEASE		= SCN_INDICATORRELEASE,
	PYSCN_CALLTIPCLICK			= SCN_CALLTIPCLICK,
	PYSCN_AUTOCSELECTION		= SCN_AUTOCSELECTION,
	PYSCN_AUTOCCANCELLED		= SCN_AUTOCCANCELLED,
	PYSCN_AUTOCCHARDELETED		= SCN_AUTOCCHARDELETED
};

#endif
