name: Continuous Integration

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2016
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: "Download and install sandcastle"
      run: |
           $url = "https://github.com/EWSoftware/SHFB/releases/download/v2020.3.6.0/SHFBInstaller_v2020.3.6.0.zip"
           $output = "$env:GITHUB_WORKSPACE\SHFBInstaller_v2020.3.6.0.zip"
           (New-Object System.Net.WebClient).DownloadFile($url, $output)
           7z x -y SHFBInstaller_v2020.3.6.0.zip | Out-Null
           Write-Host "Installing MSI..."
           cmd /c start /wait msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet
           Write-Host "Installing VSIX..."
           . "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VSIXInstaller.exe" /q /a InstallResources\SHFBVisualStudioPackage_VS2017AndLater.vsix
           Write-Host "Sandcastle installed" -ForegroundColor Green
      shell: pwsh
      working-directory: .


    - name: restore
      working-directory: .
      run: msbuild PythonScript.sln /m /verbosity:minimal /t:restore /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: MSBuild of solution
      working-directory: .
      run: msbuild PythonScript.sln /m /verbosity:minimal /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: Setup NuGet.exe
      if: matrix.build_configuration == 'Release'
      uses: nuget/setup-nuget@v1

