<html>
	<head>
		<title>Python Script - Plugin for Notepad++</title>
		<link rel="stylesheet" type="text/css" href="site.css" />
	</head>
<body>
<table border="0" width="100%">
	<tr>
		<td><a href="http://www.python.org/"><img border="0" src="images/python-logo.png" height="150" /></a></td>
		<td align="right"><a href="http://www.notepad-plus-plus.org/"><img border="0" src="images/nppLogo.png"/></a></td>
		<td align="right" width="149"><a href="http://github.com/davegb3/PythonScript"><img border="0" src="images/forkme_right_red_aa0000.png"/></a></td>
	</tr>
</table>
<hr>
<table border="0" width="100%">

<tr>
	<td width="200" class="nav" valign="top">
	<!-- Nav cell -->
	<br/><a href="index.shtml">home</a>
	<br/><a href="download.shtml">download</a>	
	<br/><a href="http://npppythonscript.sourceforge.net/docs/latest/">documentation</a>
	<br/><a href="http://sourceforge.net/projects/npppythonscript/forums">forums</a>
	<br/><a href="source.shtml">source code</a>
	<br/><a href="http://sourceforge.net/projects/npppythonscript/">project</a>
	<br/><a href="changelog.shtml">change log</a>
	<br/><a href="donations.shtml">charity donations</a>
	<br/>
	
	<br/>
	<br/>
	<br/>
Latest Version: 1.0.8.0
	<br/>
	<br/>
	<br/>
	License: <a href="http://www.gnu.org/licenses/gpl-3.0.html">GPL3</a>
	<br/><br/><br/><br/><br/>
	<script type="text/javascript"><!--
	google_ad_client = "pub-8311000309957298";
	/* 160x600, created 9/27/10 */
	google_ad_slot = "4869707314";
	google_ad_width = 160;
	google_ad_height = 600;
	//-->
	</script>
	<script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
	</script>
	<div class="germany">
	<table border="0"><tr><td valign="center"><img align="center" src="images/germany.png" /></td><td valign="center">MADE IN GERMANY</td></tr></table>
	</div>
	<br/>
	<a href="http://sourceforge.net/projects/npppythonscript"><img src="http://sflogo.sourceforge.net/sflogo.php?group_id=337487&amp;type=10" width="80" height="15" alt="Get Notepad++ Python Script at SourceForge.net. Fast, secure and Free Open Source software downloads" /></a>
	</td>
	<td class="mainContent" valign="top">
	<!-- Main content -->