<html>
	<head>
		<title>Python Script - Plugin for Notepad++</title>
		<link rel="stylesheet" type="text/css" href="site.css" />
	</head>
<body>
<table border="0" width="100%">
	<tr>
		<td><a href="http://www.python.org/"><img border="0" src="images/python-logo.png" height="150" /></a></td>
		<td align="right"><a href="http://www.notepad-plus-plus.org/"><img border="0" src="images/nppLogo.png"/></a></td>
		<td align="right" width="149"><a href="http://github.com/davegb3/PythonScript"><img border="0" src="images/forkme_right_red_aa0000.png"/></a></td>
	</tr>
</table>
<hr>
<table border="0" width="100%">

<tr>
	<td width="200" class="nav" valign="top">
	<!-- Nav cell -->
	<br/><a href="index.shtml">home</a>
	<br/><a href="download.shtml">download</a>	
	<br/><a href="http://npppythonscript.sourceforge.net/docs/latest/">documentation</a>
	<br/><a href="http://sourceforge.net/apps/phpbb/npppythonscript/index.php">forums</a>
	<br/><a href="source.shtml">source code</a>
	<br/><a href="http://sourceforge.net/projects/npppythonscript/">project</a>
	<br/>
	<br/>
	<br/>
	<br/>
	Latest Version: 0.6.3.0
	<br/>
	<br/>
	License: <a href="http://www.gnu.org/licenses/gpl-2.0.html">GPL2</a>
	</td>
	<td class="mainContent">
	<!-- Main content -->